packages/webview_flutter/lib/webview_flutter_tizen.dart, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
* Implement dispatchKeyDownEvent and dispatchKeyUpEvent
* Translate ecore key values to KeyValues for webview
=> Handle key events for tizen webview

packages/webview_flutter/tizen/inc/lwe/LWEWebView.h, packages/webview_flutter/tizen/src/webview.cc
=> [webview_flutter_dev] Enable gl compositor at LWE

packages/path_provider/CHANGELOG.md, packages/path_provider/README.md, packages/path_provider/example/pubspec.yaml, packages/path_provider/example/tizen/Runner.csproj, packages/path_provider/example/tizen/tizen-manifest.xml, packages/path_provider/pubspec.yaml
- Update path_provider and path_provider_platform_interface
- Remove permission_handler_tizen from dev_dependencies
- Update the plugin version to 1.0.1
=> [path_provider] Update package dependencies

packages/sensors/CHANGELOG.md, packages/sensors/README.md, packages/sensors/example/pubspec.yaml, packages/sensors/example/tizen/Runner.csproj, packages/sensors/example/tizen/tizen-manifest.xml, packages/sensors/pubspec.yaml, packages/sensors/tizen/project_def.prop
Also refer to the CHANGELOG file for details.
=> [sensors] Migrate to Tizen 4.0

packages/webview_flutter/tizen/inc/lwe/LWEWebView.h, packages/webview_flutter/tizen/src/webview.cc
=> [webview_flutter] Update LWE

packages/webview_flutter/tizen/src/webview.cc
=> [webview_flutter] Optimize tbm allocation

packages/webview_flutter/lib/webview_flutter_tizen.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/project_def.prop, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc, packages/webview_flutter/tizen/src/webview_flutter_tizen_plugin.cc
* Update the code by the header name changes in flutter engine
* Add an unimplemented function for flutter sdk
* Add a cookie-enabled lightweight-web-engine library
* Fix a rpath bug
* Code cleanup
=> [webview_flutter] Update code by flutter version-up

packages/camera/example/tizen/tizen-manifest.xml, packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc, packages/camera/tizen/src/log.h, packages/camera/tizen/src/permission_manager.cc, packages/camera/tizen/src/permission_manager.h
* Request camera permission when initializing
* Add some macros for convenience
* Add camera privilege to tizen-manifest.xml
=> [camera] Implement permission_manager

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/device_method_channel.cc, packages/camera/tizen/src/device_method_channel.h, packages/camera/tizen/src/orientation_event_listener.cc, packages/camera/tizen/src/orientation_event_listener.h
=> [camera] Add orientation_event_listener

packages/permission_handler/tizen/src/app_settings_manager.cc, packages/permission_handler/tizen/src/permission_handler_tizen_plugin.cc
I found [this error](https://github.com/flutter-tizen/flutter-tizen/issues/71) during integration testing. Let me apply this workaround before the plugin is published on pub.dev.
=> [permission_handler] Hot fix for glibc dependency issue

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_method_channel.cc, packages/camera/tizen/src/camera_plugin.cc, packages/camera/tizen/src/device_method_channel.cc, packages/camera/tizen/src/orientation_manager.cc, packages/camera/tizen/src/orientation_manager.h
* Flip an Image when using the front camera
* Use device orientation
* Mimic Android capture file path
=> [camera] Implement takePicture

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc
* Return result as a boolean type in camera device API wrapper function
* Use the capture file format explicitly as JPEG
=> [camera] Implement setFocusMode

README.md
Adds flutter_tts_tizen and webview_flutter_tizen.
=> Add packages in README

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc
* Clean-up codes
* Fix a crash when Disposing camera
* ExposureMode.locked is not supported on TM1
=> [camera] Implement setExposureMode

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc, packages/camera/tizen/src/orientation_manager.cc, packages/camera/tizen/src/orientation_manager.h, packages/camera/tizen/src/permission_manager.cc
* Fix build warning
* Update minor things
=> [camera] Implement setFocusPoint

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc
* Replace if-statement about enumerable with switch
* Fix wrong log message
=> [camera] Implement setFlashMode

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/integration_test/webview_flutter_tizen_test.dart, packages/webview_flutter/example/lib/main.dart, packages/webview_flutter/example/pubspec.yaml, packages/webview_flutter/example/test_driver/integration_test.dart, packages/webview_flutter/lib/webview_flutter_tizen.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc, packages/webview_flutter/tizen/src/webview_factory.h, packages/webview_flutter/tizen/src/webview_flutter_tizen_plugin.cc
* Migrate to Dart 2.12 and Flutter 2.0
* Update Flutter and Samsung copyright information
* Update webview_flutter_tizen to use platform view interface
* Update example and integration_test
* Update webivew_flutter to 2.0.4
=> [webview_flutter] Up version from 1.0.6 to 2.0.4

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc
* Implement get{Max|min}ZoomLevel
=> [camera] Implement setZoomLevel

packages/webview_flutter/tizen/src/webview.cc
* Change to a user library built based on Tizen 5.5
* Change std::string's data() to c_str()
* Fix a minor bug
=> [webview_flutter] Update user library for Tizen 5.5

packages/camera/example/tizen/tizen-manifest.xml, packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc, packages/camera/tizen/src/permission_manager.cc, packages/camera/tizen/src/permission_manager.h
**This PR includes :**
* [camera] Use 'Camera' as a wrapper function name prefix
* [camera] Request permissions as async callchain
**Note**
This implementation uses an asynchronous request chain for multiple permissions, 
because multiple privileges in single API call are supported from Tizen 5.0
=> [camera] Request a recorder permission

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc, packages/camera/tizen/src/log.h
* Implement {start|stop|pause|resume}Recording
* Cleanup code
=> [camera] Implement video recording

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc, packages/camera/tizen/src/orientation_manager.cc, packages/camera/tizen/src/orientation_manager.h
=> [camera] Implement lockCaptureOrientation

packages/camera/example/tizen/Runner.csproj, packages/camera/example/tizen/tizen-manifest.xml, packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc
* Update project files to latest
=> [camera] Improve zoom behavior

packages/webview_flutter/tizen/project_def.prop
Support for arm64
- Including lwe so for aarch64
- Tested on Raspberry Pi 4.
=> [webview_flutter] support arm64

packages/camera/README.md, packages/camera/example/README.md
=> [camera] Update README

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc
* If enable_audio is false, disable audio track when recording video
=> [camera] Use enable_audio argument

packages/google_maps_flutter/example/assets/map.html, packages/google_maps_flutter/lib/google_maps_flutter_tizen.dart, packages/google_maps_flutter/lib/src/convert.dart, packages/google_maps_flutter/lib/src/google_maps_controller.dart
* Create a map through assets/map.html
* Parse initialization options
* Support only web-based options
=> [google_maps] Initialize with google map options

packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc
This PR also includes: 
* [camera] Introduce CameraDeviceError
* [camera] Update minor things
* [camera] Fix a bug related to zoom
* [camera] Use LOG_WARN instead of LOG_ERROR
=>  [camera] Implement {GetMin|GetMax|Set}Exposure

packages/camera/example/tizen/Runner.csproj
=> [camera] Migrate example app host to latest

packages/google_maps_flutter/lib/src/convert.dart, packages/google_maps_flutter/lib/src/google_maps_controller.dart
* Add a setOptions option to set options different with initial options
* Add a restriction option for supporting camera target bounds property
* Add a 'bounds_changed' listener function for testing. This is initial implementation.
=> [google_maps] Add additional google map options

packages/google_maps_flutter/lib/src/google_maps_controller.dart
* Attach bounds_changed, idle, click, rightclick listeners to a google map's stream controller
* Add getZoomLevel API
=> [google_maps] Register listeners to google map

packages/google_maps_flutter/lib/src/convert.dart, packages/google_maps_flutter/lib/src/google_maps_controller.dart
* Attach/Detach a traffic layer to google map
* Fix a parsing bug regarding a getCameraBound option
=> [google_maps] Set traffic layer to map

packages/camera/tizen/src/camera_device.cc
=> [camera] Fix wrong comparison

packages/camera/CHANGELOG.md, packages/camera/README.md, packages/camera/pubspec.yaml, packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/camera/tizen/src/camera_plugin.cc
=> [camera] Apply new external texture APIs

.github/workflows/build_changed_packages.yml
* Build examples of changed packages when create pull request
=> Add github action for continuous builds

.github/workflows/build_changed_packages.yml, .github/workflows/format.yml
#125 fails check.
Changes:
- bump up flutter version: 2.0.1 -> 2.2.1
- run `apt-get update` before installing packages
=> Update github action

packages/battery/tizen/src/battery_tizen_plugin.cc, packages/battery_plus/tizen/src/battery_plus_tizen_plugin.cc, packages/connectivity/tizen/src/connectivity_tizen_plugin.cc, packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc, packages/network_info_plus/tizen/src/network_info_plus_tizen_plugin.cc, packages/wifi_info_flutter/tizen/src/wifi_info_flutter_tizen_plugin.cc
=> Get rid of the prefix "m_"

packages/battery/tizen/src/battery_tizen_plugin.cc, packages/battery_plus/tizen/src/battery_plus_tizen_plugin.cc, packages/connectivity/tizen/src/connectivity_tizen_plugin.cc, packages/connectivity_plus/tizen/src/connectivity_plus_tizen_plugin.cc, packages/device_info/CHANGELOG.md, packages/device_info/README.md, packages/device_info/pubspec.yaml, packages/device_info/tizen/src/device_info_tizen_plugin.cc, packages/sensors/tizen/src/sensors_plugin.cc, packages/sensors_plus/tizen/src/sensors_plus_plugin.cc
Changes:
- mostly code styles
- `device_info` will return empty string when information
is not available as same as `device_info_plus`
Only `device_info` updates will be published.
=> Sync code between plus and non-plus plugins

packages/permission_handler/README.md, packages/permission_handler/tizen/src/app_settings_manager.cc, packages/permission_handler/tizen/src/app_settings_manager.h, packages/permission_handler/tizen/src/permission_handler_tizen_plugin.cc, packages/permission_handler/tizen/src/type.h
* Show own permissions view instead system setting
* Remove limitation about openAppSettings in README
=> [permission_handler] Revise OpenAppSettings

packages/flutter_tts/CHANGELOG.md, packages/flutter_tts/README.md, packages/flutter_tts/pubspec.yaml
* Update CHANGELOG.md
* Update README.md
=> [flutter_tts] Update version

packages/permission_handler/CHANGELOG.md, packages/permission_handler/README.md, packages/permission_handler/pubspec.yaml
* Update CHANGELOG.md
* Update README.md
=> [permission_handler] Update version

.github/workflows/build.yml, README.md
=> Add a build badge

packages/webview_flutter/tizen/src/webview.cc
* This is missing part of #146
=> [webview_flutter] Remove unnecessary parts

analysis_options.yaml
=> Do not exclude examples from analysis

packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/example/integration_test/video_player_test.dart, packages/video_player/example/test_driver/integration_test.dart, packages/video_player/example/test_driver/video_player.dart, packages/video_player/example/test_driver/video_player_test.dart, packages/video_player/pubspec.yaml, packages/video_player/tizen/src/video_player.cc
- Update integration_test
- Update CHANGELOG.md and README.md
- Set paused after video completed.
=> [video_player] Update integration_test

README.md, packages/connectivity/README.md, packages/device_info/README.md
Just adds a missing entry.
I also tried [this thing](https://github.com/swift-kim/plugins/commit/39aef62b43a218bbb3b8d04e123aa7365f5ec5dd) but it didn't actually look very good.
=> Add messageport_tizen to README

packages/flutter_tts/CHANGELOG.md, packages/flutter_tts/README.md, packages/flutter_tts/pubspec.yaml, packages/flutter_tts/tizen/project_def.prop, packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc, packages/flutter_tts/tizen/src/text_to_speech.cc, packages/flutter_tts/tizen/src/text_to_speech.h
=> [flutter_tts] Refactor flutter_tts

packages/audioplayers/CHANGELOG.md, packages/audioplayers/README.md, packages/audioplayers/example/integration_test/audioplayers_test.dart, packages/audioplayers/example/pubspec.yaml, packages/audioplayers/example/test_driver/integration_test.dart, packages/audioplayers/pubspec.yaml, packages/audioplayers/tizen/src/audioplayers_tizen_plugin.cc
- Add integration test
- Update CHANGELOG.md and README.md
- Fix the timer doesn't work on tizen tv.
=> [audioplayers] Add integration test

.github/workflows/build.yml, .github/workflows/format.yml, tools/.gitignore, tools/commands/build_example.py, tools/commands/check_tidy.py, tools/commands/command_utils.py, tools/commands/integration_test.py, tools/commands/plugins.py, tools/commands/print_plugins.py, tools/run_command.py
* Enhance github actions
* Use python3
=> Introduce command runner

packages/shared_preferences/CHANGELOG.md, packages/shared_preferences/README.md, packages/shared_preferences/pubspec.yaml
=> [shared_preferences] Update version

packages/geolocator/tizen/project_def.prop, packages/geolocator/tizen/src/geolocator_tizen_plugin.cc, packages/geolocator/tizen/src/locaton_manager.cc, packages/geolocator/tizen/src/locaton_manager.h, packages/geolocator/tizen/src/permission_manager.cc, packages/geolocator/tizen/src/permission_manager.h, packages/geolocator/tizen/src/tizen_result.h
* Handle a checkPermission method
* Handle a isLocationServiceEnabled method
* Note: These are basic implementations of manager
=> [geolocator] Add location and permission manager

packages/geolocator/example/tizen/tizen-manifest.xml, packages/geolocator/tizen/src/geolocator_tizen_plugin.cc, packages/geolocator/tizen/src/permission_manager.cc, packages/geolocator/tizen/src/permission_manager.h
=> [geolocator] Implement onRequestPermission

.github/workflows/build.yml
~~Remove invalid lines in workflow script.~~ Fix workflow script.
=> Fix build workflow script

packages/geolocator/tizen/src/geolocator_tizen_plugin.cc, packages/geolocator/tizen/src/location.h, packages/geolocator/tizen/src/locaton_manager.cc, packages/geolocator/tizen/src/locaton_manager.h, packages/geolocator/tizen/src/permission_manager.cc
=> [geolocator] Implement getCurrentPosition

packages/geolocator/tizen/project_def.prop, packages/geolocator/tizen/src/geolocator_tizen_plugin.cc, packages/geolocator/tizen/src/locaton_manager.cc, packages/geolocator/tizen/src/locaton_manager.h
* change project type to staticLib
=> [geolocator] Implement getLastKnownPosition

packages/google_maps_flutter/lib/google_maps_flutter_tizen.dart, packages/google_maps_flutter/lib/src/convert.dart, packages/google_maps_flutter/lib/src/google_maps_controller.dart, packages/google_maps_flutter/lib/src/google_maps_flutter_tizen.dart, packages/google_maps_flutter/lib/src/marker.dart, packages/google_maps_flutter/lib/src/markers.dart, packages/google_maps_flutter/lib/src/types.dart, packages/google_maps_flutter/lib/src/util.dart, packages/google_maps_flutter/pubspec.yaml
* Add markersController and markerController class
* Add properties and methods related to marker for Google Map
* Add properties and methods related to infoWindow for Google Map
* Fix the widget to be launched only once
=> [google_maps_flutter] Implement initial marker module

packages/google_maps_flutter/example/tizen/tizen-manifest.xml, packages/google_maps_flutter/lib/google_maps_flutter_tizen.dart, packages/google_maps_flutter/lib/src/circle.dart, packages/google_maps_flutter/lib/src/circles.dart, packages/google_maps_flutter/lib/src/convert.dart, packages/google_maps_flutter/lib/src/google_maps_controller.dart, packages/google_maps_flutter/lib/src/google_maps_flutter_tizen.dart, packages/google_maps_flutter/lib/src/marker.dart, packages/google_maps_flutter/lib/src/markers.dart, packages/google_maps_flutter/lib/src/polygon.dart, packages/google_maps_flutter/lib/src/polygons.dart, packages/google_maps_flutter/lib/src/polyline.dart, packages/google_maps_flutter/lib/src/polylines.dart, packages/google_maps_flutter/lib/src/types.dart, packages/google_maps_flutter/lib/src/util.dart, packages/google_maps_flutter/pubspec.yaml
* Add polyline(s)Controller, polygon(s)Controller and circle(s)Controller classes
* Add properties and methods related to polyline for Google Map
* Add properties and methods related to polygon for Google Map
* Add properties and methods related to circle for Google Map
=> [google_maps_flutter] Implement polyline, polygon and circle module

packages/webview_flutter/tizen/src/webview.cc
=> [webview_flutter] Fix parameter extraction bug on loadUrl

packages/geolocator/tizen/src/geolocator_tizen_plugin.cc, packages/geolocator/tizen/src/locaton_manager.cc, packages/geolocator/tizen/src/locaton_manager.h
=> [geolocator] Setup channel for geolocator service update

packages/google_maps_flutter/example/integration_test/google_maps_test.dart, packages/google_maps_flutter/example/pubspec.yaml, packages/google_maps_flutter/example/test_driver/integration_test.dart, packages/google_maps_flutter/lib/src/convert.dart, packages/google_maps_flutter/lib/src/google_maps_controller.dart, packages/google_maps_flutter/lib/src/google_maps_flutter_tizen.dart
* Add integration tests and test driver for google_map_flutter_tizen
* google_map_flutter version up
* Check invalid mapStyle
* Add debugging methods for integration tests
* Update getScreenCoordinate API
=> [google_maps_flutter] Add integration tests

packages/geolocator/tizen/src/geolocator_tizen_plugin.cc, packages/geolocator/tizen/src/locaton_manager.cc, packages/geolocator/tizen/src/locaton_manager.h
* Implement Set/UnsetOnLocationUpdated
=> [geolocator] Setup channel for geolocator updates

packages/geolocator/example/tizen/tizen-manifest.xml, packages/geolocator/tizen/src/geolocator_tizen_plugin.cc, packages/geolocator/tizen/src/setting.cc, packages/geolocator/tizen/src/setting.h
=> [geolocator] Implement open App/location settings

packages/geolocator/example/integration_test/geolocator_test.dart, packages/geolocator/example/lib/main.dart, packages/geolocator/example/pubspec.yaml, packages/geolocator/example/test_driver/integration_test.dart
* Implement own integration tests
* Change name from _geolocatorAndroid to _geolocatorPlatform in
example/main.dart
* Sort pubspec dependencies
=> [geolocator] Add integration tests

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml
* Update LWE binary for supporting google_map_flutter_tizen
=> [webview_flutter] Update lightweight web engine binary

packages/geolocator/CHANGELOG.md, packages/geolocator/README.md, packages/geolocator/example/README.md, packages/geolocator/pubspec.yaml
* Update CHANGELOG.md, example/README.md
* Update version
=> [geolocator] Update README.md

.github/labeler.yml, .github/workflows/pull_request_label.yml
=> Add auto labeler on Pull request

packages/geolocator/analysis_options.yaml, packages/geolocator/pubspec.yaml
=> [geolocator] Add missing analysis_options.yaml

packages/audioplayers/example/lib/main.dart
=> [audioplayers] Use ElevatedButton instead

packages/battery_plus/example/integration_test/battery_plus_test.dart, packages/connectivity_plus/example/integration_test/connectivity_plus_test.dart, packages/device_info_plus/example/integration_test/device_info_plus_test.dart, packages/device_info_plus/example/lib/main.dart, packages/flutter_tts/example/integration_test/flutter_tts_test.dart, packages/package_info_plus/example/integration_test/package_info_plus_test.dart, packages/permission_handler/example/integration_test/permission_handler_test.dart
=> [multi-packages] Omit type annotations for local variable

packages/webview_flutter/tizen/src/buffer_pool.cc, packages/webview_flutter/tizen/src/buffer_pool.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
Include 2 things:
- Add surface for synchronization
- Use the memory pool evenly
=> [webview_flutter] Update surface management logic

packages/messageport/lib/src/messageport_manager.dart, packages/path_provider/lib/src/app_common.dart, packages/path_provider/lib/src/storage.dart, packages/share_plus/example/lib/main.dart, packages/shared_preferences/pubspec.yaml, packages/video_player/example/pubspec.yaml, packages/video_player/pubspec.yaml, packages/wakelock/example/integration_test/wakelock_test.dart, packages/webview_flutter/example/lib/main.dart, packages/webview_flutter/lib/src/platform_view_tizen.dart
=> [multi-packages] Fix various lint issues

.github/workflows/analyze.yml, tools/commands/build_example.py
* Change file name to analyze.yml, more comprehensively
=> Add an action to analyze packages

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/buffer_pool.cc, packages/webview_flutter/tizen/src/buffer_pool.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
Resolve https://github.com/flutter-tizen/plugins/issues/214
=> [webview_flutter] Fix buffer synchronization issue

packages/wakelock/CHANGELOG.md, packages/wakelock/README.md, packages/wakelock/example/pubspec.yaml, packages/wakelock/pubspec.yaml, packages/wakelock/tizen/src/wakelock_tizen_plugin.cc
~~Build fails~~Runtime error occurs after [this change](https://github.com/creativecreatorormaybenot/wakelock/pull/137/files), I've updated the implementation.
=> [wakelock] Bump up platform interface and update implementation

.github/workflows/analyze.yml
=> Use dart analyze for CI

packages/network_info_plus/CHANGELOG.md, packages/network_info_plus/README.md, packages/network_info_plus/pubspec.yaml, packages/network_info_plus/tizen/src/network_info_plus_tizen_plugin.cc
Fixes https://github.sec.samsung.net/f-project/home/issues/51 (internal repo).
=> [network_info_plus] Handle wifi info retrieve failure case

packages/video_player/tizen/src/video_player.cc
=> Show first frame after player prepared

packages/geolocator/CHANGELOG.md, packages/geolocator/README.md, packages/geolocator/example/integration_test/geolocator_test.dart, packages/geolocator/example/lib/main.dart, packages/geolocator/example/pubspec.yaml, packages/geolocator/example/test_driver/integration_test.dart, packages/geolocator/example/tizen/Runner.csproj, packages/geolocator/example/tizen/tizen-manifest.xml, packages/geolocator/pubspec.yaml, packages/geolocator/tizen/src/geolocator_tizen_plugin.cc, packages/geolocator/tizen/src/location.h, packages/geolocator/tizen/src/tizen_result.h
Just some cleanups. No implementation change.
=> [geolocator] Update geolocator to 8.0.0

packages/image_picker/CHANGELOG.md, packages/image_picker/README.md, packages/image_picker/example/integration_test/image_picker_test.dart, packages/image_picker/example/lib/main.dart, packages/image_picker/example/pubspec.yaml, packages/image_picker/example/test_driver/integration_test.dart, packages/image_picker/example/tizen/Runner.csproj, packages/image_picker/example/tizen/tizen-manifest.xml, packages/image_picker/pubspec.yaml, packages/image_picker/tizen/src/image_picker_tizen_plugin.cc, tools/recipe.yaml
- Adds support for `pickMultiImage`.
- Update the example app.
- Minor cleanups.
Note: The user facing API of image_picker has changed (e.g. `getImage` to `pickImage`). See https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker#migrating-to-082 for details.
=> [image_picker] Update image_picker to 0.8.4

packages/google_maps_flutter/.gitignore, packages/integration_test/.gitignore, packages/messageport/.gitignore, packages/path_provider/.gitignore, packages/shared_preferences/.gitignore, packages/url_launcher/.gitignore
6 packages are missing .gitignore files.
=> Add missing .gitignore files

packages/audioplayers/example/lib/player_widget.dart, packages/audioplayers/example/lib/tabs/global.dart, packages/camera/example/integration_test/camera_test.dart, packages/connectivity_plus/example/lib/main.dart, packages/google_maps_flutter/example/integration_test/google_maps_test.dart, packages/google_maps_flutter/example/lib/lite_mode.dart, packages/google_maps_flutter/example/lib/map_click.dart, packages/google_maps_flutter/example/lib/map_coordinates.dart, packages/google_maps_flutter/example/lib/place_marker.dart, packages/google_maps_flutter/example/lib/scrolling_map.dart, packages/messageport/example/integration_test/messageport_test.dart, packages/share/example/lib/image_previews.dart, packages/share_plus/example/lib/image_previews.dart, packages/sqflite/example/integration_test/sqflite_test.dart, packages/sqflite/example/lib/src/item_widget.dart, packages/sqflite/example/lib/src/main_item_widget.dart, packages/sqflite/example/lib/test_page.dart, packages/video_player/example/lib/main.dart, packages/webview_flutter/example/integration_test/webview_flutter_test.dart, packages/webview_flutter/lib/webview_flutter_tizen.dart
This change is still compatible with Dart 2.14 and can be safely merged without waiting for the flutter-tizen 2.8 release.
=> Resolve analyzer issues for Dart 2.15

.github/workflows/build.yml, .github/workflows/integration_test.yml, .github/workflows/pull_request_label.yml, tools/commands/check_tidy.py, tools/commands/integration_test.py, tools/recipe.yaml
Only use the recipe file without having to specify excluded packages (`--exclude`) again, as suggested in https://github.com/flutter-tizen/plugins/issues/272#issuecomment-964024353.
=> Update the test recipe and workflow

tools/commands/integration_test.py
Issue and solution suggested by @swift-kim, thanks!
~~The last commit will be reverted after test passes.~~ passed.
=> Reduce test failures by polling device boot status

packages/battery/CHANGELOG.md, packages/battery/README.md, packages/battery/pubspec.yaml, packages/connectivity/CHANGELOG.md, packages/connectivity/README.md, packages/connectivity/pubspec.yaml, packages/device_info/CHANGELOG.md, packages/device_info/README.md, packages/device_info/pubspec.yaml, packages/package_info/CHANGELOG.md, packages/package_info/README.md, packages/package_info/pubspec.yaml, packages/sensors/CHANGELOG.md, packages/sensors/README.md, packages/sensors/pubspec.yaml, packages/share/CHANGELOG.md, packages/share/README.md, packages/share/pubspec.yaml, packages/wifi_info_flutter/CHANGELOG.md, packages/wifi_info_flutter/README.md, packages/wifi_info_flutter/pubspec.yaml
Part of https://github.com/flutter-tizen/plugins/issues/308.
The source files will be removed from the tree after this PR.
=> Add deprecation notices

packages/package_info_plus/CHANGELOG.md, packages/package_info_plus/README.md, packages/package_info_plus/example/integration_test/package_info_plus_test.dart, packages/package_info_plus/example/pubspec.yaml, packages/package_info_plus/example/test_driver/integration_test.dart, packages/package_info_plus/example/tizen/Runner.csproj, packages/package_info_plus/example/tizen/tizen-manifest.xml, packages/package_info_plus/pubspec.yaml, packages/package_info_plus/tizen/src/package_info_plus_tizen_plugin.cc
For https://github.com/flutter-tizen/flutter-tizen/pull/303#issuecomment-1001450222.
=> [package_info_plus] Update package_info_plus to 1.3.0

packages/sqflite/example/lib/open_test_page.dart
=> [sqflite] Resolve dart analyze issue

tools/lib/src/device.dart, tools/lib/src/integration_test_command.dart, tools/lib/src/tizen_sdk.dart
Use the term "serial" to be consistent with sdb.
=> Rename id to serial

packages/audioplayers/example/tizen/Runner.csproj, packages/battery_plus/example/tizen/Runner.csproj, packages/camera/example/tizen/Runner.csproj, packages/connectivity_plus/example/tizen/Runner.csproj, packages/device_info_plus/example/tizen/Runner.csproj, packages/flutter_tts/example/tizen/Runner.csproj, packages/geolocator/example/tizen/Runner.csproj, packages/google_maps_flutter/example/tizen/Runner.csproj, packages/image_picker/example/tizen/Runner.csproj, packages/integration_test/example/tizen/Runner.csproj, packages/messageport/example/tizen/Runner.csproj, packages/network_info_plus/example/tizen/Runner.csproj, packages/package_info_plus/example/tizen/Runner.csproj, packages/path_provider/example/tizen/Runner.csproj, packages/permission_handler/example/tizen/Runner.csproj, packages/sensors_plus/example/tizen/Runner.csproj, packages/share_plus/example/tizen/Runner.csproj, packages/shared_preferences/example/tizen/Runner.csproj, packages/sqflite/example/tizen/Runner.csproj, packages/tizen_app_manager/example/tizen/Runner.csproj, packages/tizen_audio_manager/example/tizen/Runner.csproj, packages/tizen_log/example/tizen/Runner.csproj, packages/tizen_notification/example/tizen/Runner.csproj, packages/tizen_package_manager/example/tizen/Runner.csproj, packages/url_launcher/example/tizen/Runner.csproj, packages/video_player/example/tizen/Runner.csproj, packages/wakelock/example/tizen/Runner.csproj, packages/wearable_rotary/example/tizen/Runner.csproj, packages/webview_flutter/example/tizen/Runner.csproj
Clean up according to the updated template.
Please refer to https://github.com/flutter-tizen/flutter-tizen/pull/338.
=> Remove DebugType properties from Runner.csproj

packages/package_info_plus/tizen/src/package_info_plus_tizen_plugin.cc
Remove use of `goto`.
Contributes to https://github.com/flutter-tizen/plugins/issues/354.
=> [package_info_plus] Minor refactoring

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc
=> [webview_flutter] Support background color property

packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview_flutter_tizen_plugin.cc
Depends on https://github.com/flutter-tizen/flutter-tizen/pull/358
=> [webview_flutter] Apply flutter-tizen api change

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/pubspec.yaml, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/buffer_pool.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc, packages/webview_flutter/tizen/src/webview_factory.h, packages/webview_flutter/tizen/src/webview_flutter_tizen_plugin.cc
* Remove unused code.
* Fix build warnings.
=> [webview_flutter] Remove unused code

.github/recipe.yaml, tools/lib/src/integration_test_command.dart
Left out `else`. Tool currently fails if ran without recipe file.
=> Fix an error when run without recipe and update the recipe to test on 6.5 TV emulators

analysis_options.yaml, packages/integration_test/example/lib/main.dart, packages/messageport/example/lib/main.dart, packages/path_provider/CHANGELOG.md, packages/path_provider/example/lib/main.dart, packages/shared_preferences/example/lib/main.dart, packages/shared_preferences/example/pubspec.yaml, packages/shared_preferences/lib/shared_preferences_tizen.dart, packages/shared_preferences/lib/src/bindings.dart, packages/shared_preferences/pubspec.yaml, packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart, packages/tizen_app_control/example/lib/main.dart, packages/tizen_app_control/lib/app_control.dart, packages/tizen_app_control/lib/src/ffi.dart, packages/tizen_app_control/lib/src/utils.dart, packages/tizen_app_manager/example/lib/main.dart, packages/tizen_app_manager/lib/app_manager.dart, packages/tizen_app_manager/lib/src/app_context.dart, packages/tizen_audio_manager/example/lib/main.dart, packages/tizen_log/example/lib/main.dart, packages/tizen_notification/example/lib/main.dart, packages/tizen_notification/lib/tizen_notification.dart, packages/tizen_package_manager/example/lib/main.dart, packages/url_launcher/example/lib/main.dart, packages/url_launcher/example/pubspec.yaml, packages/url_launcher/pubspec.yaml, packages/wearable_rotary/example/lib/custom_page_view.dart, packages/wearable_rotary/example/lib/main.dart
Part of https://github.com/flutter-tizen/plugins/issues/389.
=> Sync flutter/plugins analysis options

packages/image_picker/CHANGELOG.md, packages/image_picker/analysis_options.yaml, packages/image_picker/example/lib/main.dart, packages/image_picker/example/pubspec.yaml, packages/image_picker/pubspec.yaml
Contributes to https://github.com/flutter-tizen/plugins/issues/389. Please see the changelog file for details.
=> [image_picker] Migrate to new analysis options

packages/camera/CHANGELOG.md, packages/camera/README.md, packages/camera/analysis_options.yaml, packages/camera/example/integration_test/camera_test.dart, packages/camera/example/lib/main.dart, packages/camera/example/pubspec.yaml, packages/camera/pubspec.yaml
Part of https://github.com/flutter-tizen/plugins/issues/389.
=> [camera] Migrate to new analysis options

packages/tizen_log/CHANGELOG.md, packages/tizen_log/README.md, packages/tizen_log/example/pubspec.yaml, packages/tizen_log/example/tizen/tizen-manifest.xml, packages/tizen_log/lib/tizen_log.dart, packages/tizen_log/pubspec.yaml
- Fix incorrect information in README (`DEBUG_MODE=debug` → `DEBUG_MODE=true`).
- Remove unnecessary Flutter and flutter_lints dependency.
- Code formatting.
=> [tizen_log] Update README

packages/tizen_app_manager/CHANGELOG.md, packages/tizen_app_manager/README.md, packages/tizen_app_manager/pubspec.yaml, packages/tizen_app_manager/tizen/src/tizen_app_manager_plugin.cc
=> [tizen_app_manager] Fix arm64 build error

packages/tizen_notification/CHANGELOG.md, packages/tizen_notification/README.md, packages/tizen_notification/example/lib/main.dart, packages/tizen_notification/pubspec.yaml
=> [tizen_notification] Update example

.github/workflows/analyze.yml, .github/workflows/build.yml, .github/workflows/integration_test.yml, .github/workflows/pull_request_label.yml, .github/workflows/release.yml
Format workflow files in a consistent manner.
=> Format CI scripts

packages/path_provider/CHANGELOG.md, packages/path_provider/README.md, packages/path_provider/lib/path_provider_tizen.dart, packages/path_provider/lib/src/app_common.dart, packages/path_provider/lib/src/storage.dart, packages/path_provider/pubspec.yaml
Reimplement using the tizen_interop package.
Contributes to https://github.com/flutter-tizen/tizen_interop/issues/9.
=> [path_provider] Add tizen_interop dependency

packages/tizen_app_manager/CHANGELOG.md, packages/tizen_app_manager/README.md, packages/tizen_app_manager/lib/src/app_context.dart, packages/tizen_app_manager/lib/src/app_manager.dart, packages/tizen_app_manager/lib/tizen_app_manager.dart, packages/tizen_app_manager/pubspec.yaml
=> [tizen_app_manager] Add tizen_interop dependency

tools/lib/src/build_examples_command.dart
Also:
- Remove clean command as building examples run in CI environment.
- Remove supporting different profiles as there's no public TV sdk.
=> Support building multiple example apps in CI

packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.h
=> [webview_flutter] Fix typo

README.md
=> Add missing package to the list of packages

packages/camera/CHANGELOG.md, packages/camera/README.md, packages/camera/lib/camera_tizen.dart, packages/camera/lib/src/type_conversion.dart, packages/camera/lib/src/utils.dart, packages/camera/pubspec.yaml, packages/camera/tizen/src/camera_method_channel.cc, packages/camera/tizen/src/camera_method_channel.h, packages/camera/tizen/src/camera_plugin.cc, packages/camera/tizen/src/device_method_channel.cc, packages/camera/tizen/src/device_method_channel.h
Contributes to https://github.com/flutter-tizen/plugins/issues/348.
`camera_tizen.dart` is a copy of camera_android's [`android_camera.dart`](https://github.com/flutter/plugins/blob/main/packages/camera/camera_android/lib/src/android_camera.dart) with a few minor modifications.
=> [camera] Switch to internal method channel

packages/tizen_rpc_port/example/client/lib/main.dart, packages/tizen_rpc_port/example/client/lib/message_client.dart, packages/tizen_rpc_port/example/message.tidl, packages/tizen_rpc_port/example/server/lib/main.dart, packages/tizen_rpc_port/example/server/lib/message_server.dart, packages/tizen_rpc_port/lib/src/proxy_base.dart
Changes:
- Modify method type of sync method.
- Changes some stub variable names.
- Removes `OnDisconnected` typedef from the client interface.
Signed-off-by: Changgyu Choi <changyu.choi@samsung.com>
=> [tizen_rpc_port] Fix interface form

packages/sqflite/example/lib/slow_test_page.dart, packages/tizen_app_manager/example/lib/main.dart, packages/tizen_rpc_port/example/client/lib/message_client.dart
Resolve lint warnings and formatting error.
@upple A change has been made to `message_client.dart` which is an auto-generated file. You may need to update the code generator (TIDLC) implementation.
=> Resolve Flutter 3.7 analyze issues

packages/tizen_app_manager/CHANGELOG.md, packages/tizen_app_manager/README.md, packages/tizen_app_manager/example/lib/main.dart, packages/tizen_app_manager/pubspec.yaml, packages/tizen_app_manager/tizen/src/tizen_app_manager_plugin.cc
Similar to https://github.com/flutter-tizen/plugins/pull/520.
=> [tizen_app_manager] Add threading to prevent app freezing

packages/flutter_webrtc/pubspec.yaml
https://github.com/flutter-tizen/plugins/pull/563#issuecomment-1541404604
=> [flutter_webrtc] Update pubspec.yaml

packages/battery_plus/CHANGELOG.md, packages/battery_plus/README.md, packages/battery_plus/example/integration_test/battery_plus_test.dart, packages/battery_plus/example/lib/main.dart, packages/battery_plus/example/pubspec.yaml, packages/battery_plus/pubspec.yaml
* Update battery_plus 2.1.3 to 4.0.1.
* Update battery_plus_platform_interface to 1.2.2
* Update flutter_lints to 2.0.1.
* Update the example app and integration_test.
=> [battery_plus] Update battery_plus to 4.0.1

packages/flutter_tts/CHANGELOG.md, packages/flutter_tts/README.md, packages/flutter_tts/example/lib/main.dart, packages/flutter_tts/example/pubspec.yaml, packages/flutter_tts/pubspec.yaml, packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc, packages/flutter_tts/tizen/src/text_to_speech.cc, packages/flutter_tts/tizen/src/text_to_speech.h
* Update flutter_tts 3.5.0 to 3.6.3.
* Update the example app.
* Add getDefaultVoice and getMaxSpeechInputLength APIs.
=> [flutter_tts] Update flutter_tts to 3.6.3

packages/permission_handler/CHANGELOG.md, packages/permission_handler/README.md, packages/permission_handler/example/lib/main.dart, packages/permission_handler/example/pubspec.yaml, packages/permission_handler/pubspec.yaml, packages/permission_handler/tizen/src/permission_handler_tizen_plugin.cc, packages/permission_handler/tizen/src/permission_manager.h, packages/permission_handler/tizen/src/permissions.h
* Update permission_handler to 10.4.3.
* Update permission_handler_platform_interface to 3.11.0.
* Update the example app.
=> [permission_handler] Update package dependency

packages/flutter_secure_storage/CHANGELOG.md, packages/flutter_secure_storage/README.md, packages/flutter_secure_storage/analysis_options.yaml, packages/flutter_secure_storage/example/lib/main.dart, packages/flutter_secure_storage/example/pubspec.yaml, packages/flutter_secure_storage/pubspec.yaml
* Update flutter_secure_storage to 9.0.0.
* Update example app.
* Increase the minimum Flutter version to 3.3.
Related to #609
=> [flutter_secure_storage] Update flutter_secure_storage to 9.0.0

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/example/integration_test/webview_flutter_test.dart, packages/webview_flutter/example/lib/main.dart, packages/webview_flutter/example/pubspec.yaml, packages/webview_flutter/lib/src/tizen_webview.dart, packages/webview_flutter/lib/src/tizen_webview_controller.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
* Update webivew_flutter to 4.2.3.
* Update webview_flutter_platform_interface to 2.3.0.
* Update integration_test.
* Implement `NavigationDelegate(onUrlChange)`.
* Increase the minimum Flutter version to 3.3.
=> [webview_flutter] Update webview_flutter to 4.2.3

packages/connectivity_plus/CHANGELOG.md, packages/connectivity_plus/README.md, packages/connectivity_plus/example/integration_test/connectivity_plus_test.dart, packages/connectivity_plus/example/lib/main.dart, packages/connectivity_plus/example/pubspec.yaml, packages/connectivity_plus/pubspec.yaml
Update connectivity_plus to 4.0.1.
Update connectivity_plus_platform_interface to 1.2.4.
Update example app.
=> [connectivity_plus] Update package dependency

packages/sensors_plus/CHANGELOG.md, packages/sensors_plus/README.md, packages/sensors_plus/example/integration_test/sensors_plus_test.dart, packages/sensors_plus/example/lib/main.dart, packages/sensors_plus/example/pubspec.yaml, packages/sensors_plus/pubspec.yaml, packages/sensors_plus/tizen/src/device_sensor.cc, packages/sensors_plus/tizen/src/device_sensor.h, packages/sensors_plus/tizen/src/sensors_plus_plugin.cc
Update sensors_plus to 3.0.2.
Update sensors_plus_platform_interface to 1.1.3.
Update the example app.
=> [sensors_plus] Update package dependency

packages/sensors_plus/CHANGELOG.md, packages/sensors_plus/README.md, packages/sensors_plus/example/integration_test/sensors_plus_test.dart, packages/sensors_plus/example/lib/main.dart, packages/sensors_plus/example/lib/snake.dart, packages/sensors_plus/example/pubspec.yaml, packages/sensors_plus/pubspec.yaml, packages/sensors_plus/tizen/src/device_sensor.cc, packages/sensors_plus/tizen/src/device_sensor.h, packages/sensors_plus/tizen/src/sensors_plus_plugin.cc
* Implement set*SamplingPeriod method call.
* Update deprecated API in integration_test.
* Update sensors_plus to 4.0.1.
* Update sensors_plus_platform_interface to 1.2.0.
=> [sensor_plus] Implement set*SamplingPeriod method call

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/example/lib/main.dart
Play Butterfly-209.mp4 from assets.
=> [video_player_avplay] Add a case that plays the video of assets to the example

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/README.md, packages/google_maps_flutter/lib/src/circle.dart, packages/google_maps_flutter/lib/src/google_maps_controller.dart, packages/google_maps_flutter/lib/src/google_maps_flutter_tizen.dart, packages/google_maps_flutter/lib/src/marker.dart, packages/google_maps_flutter/lib/src/polygon.dart, packages/google_maps_flutter/lib/src/polyline.dart, packages/google_maps_flutter/lib/src/types.dart, packages/google_maps_flutter/lib/src/util.dart, packages/google_maps_flutter/pubspec.yaml
- Update webview_flutter to 4.2.2.
- Update webview_flutter_lwe to 0.3.1.
=> [google_maps_flutter] Update webview_flutter version

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/pubspec.yaml, packages/video_player_avplay/tizen/src/media_player.cc, packages/video_player_avplay/tizen/src/plus_player.cc
Fix https://github.com/flutter-tizen/plugins/issues/701
=> [video_player_avplay]No return empty error message

packages/path_provider/CHANGELOG.md, packages/path_provider/README.md, packages/path_provider/lib/src/app_common.dart, packages/path_provider/lib/src/storage.dart, packages/path_provider/pubspec.yaml
Update tizen_interop version.
https://github.com/flutter-tizen/plugins/issues/704
=> [path_provider] Update tizen_interop to 0.3.0

packages/tizen_rpc_port/CHANGELOG.md, packages/tizen_rpc_port/README.md, packages/tizen_rpc_port/pubspec.yaml
Update tizen_interop and tizen_bundle version.
https://github.com/flutter-tizen/plugins/issues/704
=> [tizen_rpc_port] Update tizen_interop and tizen_bundle to 0.3.0 and 0.1.2

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/pubspec.yaml, packages/video_player_avplay/tizen/res/plusplayer.ini
Change "use_new_http_demuxer" value from true to false. It is only for tvplus.
if change "use_new_http_demuxer" to false, flutter app will use platfrom gst-ffmpeg library for http streaming.
=> [video_player_avplay] Update plusplayer.ini

packages/webview_flutter_lwe/CHANGELOG.md, packages/webview_flutter_lwe/README.md, packages/webview_flutter_lwe/pubspec.yaml
=> [webview_flutter_lwe] Update pub version

packages/video_player_videohole/CHANGELOG.md, packages/video_player_videohole/README.md, packages/video_player_videohole/lib/video_player.dart, packages/video_player_videohole/pubspec.yaml
=> [video_player_videohole] Add 'isCompleted' event to 'VideoPlayerEvent'

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/pubspec.yaml, packages/video_player_avplay/tizen/src/plus_player.cc
Because the type of 0 is int_32 on ARM32,  convert the type of 0 to int64_t.
=> [video_player_avplay] Fix start position out of range issue

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/README.md, packages/google_maps_flutter/example/integration_test/src/maps_controller.dart, packages/google_maps_flutter/example/integration_test/src/maps_inspector.dart, packages/google_maps_flutter/example/integration_test/src/tiles_inspector.dart, packages/google_maps_flutter/example/lib/clustering.dart, packages/google_maps_flutter/example/lib/heatmap.dart, packages/google_maps_flutter/example/lib/main.dart, packages/google_maps_flutter/example/lib/map_map_id.dart, packages/google_maps_flutter/example/lib/marker_icons.dart, packages/google_maps_flutter/example/lib/place_polygon.dart, packages/google_maps_flutter/example/pubspec.yaml, packages/google_maps_flutter/lib/src/marker.dart, packages/google_maps_flutter/pubspec.yaml
- Update google_maps_flutter to 2.10.0.
- Update google_maps_flutter_platform_interface to 2.10.0.
- Updates minimum supported SDK version to Flutter 3.22/Dart 3.4.
=> [google_maps_flutter] Update google_maps_flutter to 2.10.0

packages/flutter_secure_storage/example/integration_test/flutter_secure_storage_test.dart
=> [flutter_secure_storage] Fix analyze issue

tools/lib/src/device.dart
This option seems to be useful for test environments that don't need access to DDS(Dart Development Service).
https://github.com/flutter-tizen/plugins/actions/runs/14534140709/job/40780256549
```
2025-04-18T11:44:48.5393409Z Bad state: Failed to connect to VM Service at ws://localhost:40951/U0gfMA8WRbw=/ws.
2025-04-18T11:44:48.5395053Z This may happen if DDS is enabled. If this test was launched via `flutter drive`, try adding
2025-04-18T11:44:48.5396346Z `--no-dds`.
```
=> [integration_test] Add --no-dds option for test

packages/video_player_videohole/CHANGELOG.md, packages/video_player_videohole/README.md, packages/video_player_videohole/lib/src/video_player_tizen.dart, packages/video_player_videohole/lib/video_player.dart, packages/video_player_videohole/lib/video_player_platform_interface.dart, packages/video_player_videohole/pubspec.yaml, packages/video_player_videohole/tizen/src/media_player.cc, packages/video_player_videohole/tizen/src/video_player.cc, packages/video_player_videohole/tizen/src/video_player.h
Main change:
- Synchronize isPlaying state
=> [video_player_videohole] Synchronize isPlaying state

packages/permission_handler/CHANGELOG.md, packages/permission_handler/README.md, packages/permission_handler/example/lib/main.dart, packages/permission_handler/pubspec.yaml
* Update README.
* Update the example app.
=> [permission_handler] Update README and example

packages/video_player_videohole/CHANGELOG.md, packages/video_player_videohole/README.md, packages/video_player_videohole/example/tizen/tizen-manifest.xml, packages/video_player_videohole/lib/src/messages.g.dart, packages/video_player_videohole/lib/src/video_player_tizen.dart, packages/video_player_videohole/lib/video_player.dart, packages/video_player_videohole/lib/video_player_platform_interface.dart, packages/video_player_videohole/pigeons/messages.dart, packages/video_player_videohole/pubspec.yaml, packages/video_player_videohole/tizen/src/media_player.cc, packages/video_player_videohole/tizen/src/media_player.h, packages/video_player_videohole/tizen/src/messages.cc, packages/video_player_videohole/tizen/src/messages.h, packages/video_player_videohole/tizen/src/video_player.h, packages/video_player_videohole/tizen/src/video_player_tizen_plugin.cc
Main Changes:
- Automatically rotates video player based on device orientation
=> [video_player_videohole] Automatically rotates video player based on device orientation
