flutter-tizen/plugins

.github/workflows/dart.yml, analysis_options.yaml, packages/path_provider/pubspec.yaml, packages/shared_preferences/lib/shared_preferences_tizen.dart, packages/shared_preferences/pubspec.yaml, packages/url_launcher/example/pubspec.yaml, packages/url_launcher/lib/url_launcher_tizen.dart, packages/url_launcher/pubspec.yaml
- Use concrete version dependencies on platform interface packages (because platform interfaces are not necessarily backward compatible)
- Update analysis_options.yaml and resolve warnings
- Add a workflow (Dart)
The workflow verifies Dart code only. More checks will be added later for full analysis of other requirements.
=> Add a workflow for static analysis of Dart code

packages/integration_test/example/pubspec.yaml, packages/integration_test/pubspec.yaml, packages/path_provider/example/pubspec.yaml, packages/path_provider/pubspec.yaml, packages/sensors/example/pubspec.yaml, packages/sensors/pubspec.yaml, packages/shared_preferences/example/pubspec.yaml, packages/shared_preferences/pubspec.yaml, packages/url_launcher/example/pubspec.yaml, packages/url_launcher/pubspec.yaml
To upload the packages to pub.dev, `flutter>=1.20.0` is required.
```
pubspec.yaml allows Flutter SDK version prior to 1.20.0, which does not support having no `ios/` folder.
Please consider increasing the Flutter SDK requirement to ^1.20.0 or higher (environment.sdk.flutter) or create an `ios/` folder.
See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin
```
=> Increase the Flutter SDK requirement

packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc, packages/webview_flutter/tizen/src/webview_factory.h
* According to convention, I change the method name's the first letter from lower case to upper case.
=> Change method name's first letter

packages/webview_flutter/tizen/inc/lwe/LWEWebView.h, packages/webview_flutter/tizen/src/webview.cc
=> [webview_flutter_dev] Enable gl compositor at LWE

packages/webview_flutter/example/lib/main.dart, packages/webview_flutter/tizen/inc/lwe/LWEWebView.h, packages/webview_flutter/tizen/project_def.prop, packages/webview_flutter/tizen/src/webview.cc
Now, we can run webview test app without any preparations
Just run ``flutter-tizen run`` at example.
=> [webview_flutter_dev] Change webview interface && embedding lwe.so file

packages/webview_flutter/example/tizen/shared/res/input.html, packages/webview_flutter/lib/webview_flutter_tizen.dart
* A webview has to act like a FocusNode. So, when it is clicked or released, a FocusCallback function should be called.
=> [webview_flutter] Update webview to be focused

packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
* Change the order of the headers to build the webview plugin
* Implement the evaluateJavascript() function of the webview plugin
=> [webview_flutter] Add evaluateJavascript() function

.github/workflows/dart.yml, packages/url_launcher/CHANGELOG.md, packages/url_launcher/README.md, packages/url_launcher/example/pubspec.yaml, packages/url_launcher/example/tizen/Runner.csproj, packages/url_launcher/example/tizen/tizen-manifest.xml, packages/url_launcher/pubspec.yaml
- Use the caret (^) syntax for platform interface version
- Migrate the example to Tizen 4.0
- Small changes to the CI script
- Resolve to the oldest possible dependencies
- Remove the meaningless "dart analyze" job
=> [url_launcher] Make platform interface version constraint less tight

packages/integration_test/CHANGELOG.md, packages/integration_test/README.md, packages/integration_test/example/pubspec.yaml, packages/integration_test/example/tizen/Runner.csproj, packages/integration_test/example/tizen/tizen-manifest.xml, packages/integration_test/pubspec.yaml, packages/integration_test/tizen/project_def.prop
Refer to the CHANGELOG file for details.
=> [integration_test] Use the stable version of integration_test

packages/shared_preferences/CHANGELOG.md, packages/shared_preferences/README.md, packages/shared_preferences/example/pubspec.yaml, packages/shared_preferences/example/tizen/Runner.csproj, packages/shared_preferences/example/tizen/tizen-manifest.xml, packages/shared_preferences/pubspec.yaml
Also refer to the CHANGELOG file for details.
=> [shared_preferences] Update platform interface

packages/webview_flutter/tizen/inc/lwe/LWEWebView.h, packages/webview_flutter/tizen/inc/lwe/PlatformIntegrationData.h, packages/webview_flutter/tizen/src/webview.cc
=> [webview_flutter] Update LWE

packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc
* This plugin exposes a single method called `postMessage` to JavaScript.
* This method sends a message over a method channel to the Dart code.
=> [webview_flutter] Implement addJavascriptChannels()

packages/webview_flutter/tizen/src/webview.cc
* Implement removeJavascriptChannels() method in native side
* Register the callback functions to be invoked when native webview's events like onPageStarted() and onPageFinished() happen
=> [webview_flutter] Add removeJavascriptChannels API and Callbacks

packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc
* The NavigationDelegate handler decides how to handle navigation actions
* When the handler is null, all navigation actions are allowed
* Implement the onWebResourceError callback to report web resource loading error
* The callback's error codes use ones provided by lightweight-web-engine on tizen
=> [webview_flutter] Add NavigationDelegate and onWebResourceError

packages/webview_flutter/tizen/inc/lwe/LWEWebView.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
* The userAgent(), updateSetting(), getTitle(), scrollTo() and scrollBy() APIs are added
* The member variable 'currentUrl_' is changed to the webview's GetURL()
* For above APIs, liblightweight-web-engine.mobile.so and header files are updated
=> Add some APIs

packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/inc/lwe/LWEWebView.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
* Implement a method channel for handling cookies
* Add GetScrollX and GetScrollY APIs
* Add code to set UserAgent when initializing the webview
=> [webview_flutter] Add cookie and scroll APIs

packages/url_launcher/CHANGELOG.md, packages/url_launcher/README.md, packages/url_launcher/example/pubspec.yaml, packages/url_launcher/lib/url_launcher_tizen.dart, packages/url_launcher/pubspec.yaml
The `linkDelegate` property has been added in 1.0.9 to support the newly proposed Link widget. For more information on it, see the relevant changes (#3154, #3177) in the [flutter/plugins](https://github.com/flutter/plugins) repo and the [source code](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher/lib/src/link.dart).
`null` can be returned to enable a fallback to `DefaultLinkDelegate` on non-web platforms.
=> [url_launcher] Update platform interface to 1.0.9

packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
* Pass a composition event sent by the flutter engine to the webview plugin
* Handle a clear focus event
=> [webview_flutter] Handle CompositionEvent

packages/webview_flutter/README.md, packages/webview_flutter/example/pubspec.yaml, packages/webview_flutter/pubspec.yaml
* Update README
* Update pubspec
=> [webview_flutter] Update README and pubspec

packages/camera/tizen/src/camera_device.cc
* Even if I send this to false when opening camera,
the focus point request arrived to method handler normally
=> [camera] Send focusPointSupported as a true

packages/audioplayers/tizen/src/log.h, packages/battery/tizen/src/battery_tizen_plugin.cc, packages/battery/tizen/src/log.h, packages/camera/tizen/src/log.h, packages/connectivity/tizen/src/log.h, packages/device_info/tizen/src/device_info_tizen_plugin.cc, packages/device_info/tizen/src/log.h, packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc, packages/flutter_tts/tizen/src/log.h, packages/image_picker/tizen/src/image_picker_tizen_plugin.cc, packages/image_picker/tizen/src/image_resize.cc, packages/image_picker/tizen/src/log.h, packages/integration_test/tizen/src/log.h, packages/package_info/tizen/src/log.h, packages/package_info/tizen/src/package_info_tizen_plugin.cc, packages/permission_handler/tizen/src/app_settings_manager.cc, packages/permission_handler/tizen/src/log.h, packages/permission_handler/tizen/src/permission_manager.cc, packages/sensors/tizen/src/log.h, packages/sensors/tizen/src/sensors_plugin.cc, packages/share/tizen/src/log.h, packages/share/tizen/src/share_tizen_plugin.cc, packages/video_player/tizen/src/log.h, packages/video_player/tizen/src/video_player.cc, packages/video_player/tizen/src/video_player_error.h, packages/video_player/tizen/src/video_player_tizen_plugin.cc, packages/wakelock/tizen/src/log.h, packages/webview_flutter/tizen/src/log.h, packages/wifi_info_flutter/tizen/src/log.h
- Avoid the error converter function and use `get_error_message()` instead.
- Use the new log.h template (`__FILE__` to `__MODULE__`).
=> Use get_error_message() whenever possible

packages/audioplayers/example/pubspec.yaml, packages/battery/example/pubspec.yaml, packages/camera/tizen/src/camera_device.cc, packages/connectivity/example/pubspec.yaml, packages/device_info/example/pubspec.yaml, packages/device_info/tizen/src/device_info_tizen_plugin.cc, packages/flutter_tts/example/pubspec.yaml, packages/image_picker/example/pubspec.yaml, packages/image_picker/tizen/src/image_picker_tizen_plugin.cc, packages/image_picker/tizen/src/image_resize.cc, packages/integration_test/example/pubspec.yaml, packages/package_info/example/pubspec.yaml, packages/package_info/tizen/src/package_info_tizen_plugin.cc, packages/path_provider/example/pubspec.yaml, packages/permission_handler/tizen/src/app_settings_manager.cc, packages/sensors/example/pubspec.yaml, packages/share/example/pubspec.yaml, packages/share/tizen/src/share_tizen_plugin.cc, packages/shared_preferences/example/pubspec.yaml, packages/url_launcher/example/pubspec.yaml, packages/video_player/example/pubspec.yaml, packages/wakelock/example/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc, packages/wifi_info_flutter/example/pubspec.yaml, packages/wifi_info_flutter/tizen/src/wifi_info_flutter_tizen_plugin.cc
=> Cleanup minor things

packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc, packages/webview_flutter/tizen/src/webview_factory.h, packages/webview_flutter/tizen/src/webview_flutter_tizen_plugin.cc
=> [webview_flutter] Apply texture api change

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/inc/lwe/LWEWebView.h, packages/webview_flutter/tizen/project_def.prop, packages/webview_flutter/tizen/src/buffer_pool.cc, packages/webview_flutter/tizen/src/buffer_pool.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
* Update lightweight web engine binary
* Update version && change log
* Enable resize function
=> [webview_flutter] Update minor things

packages/battery_plus/README.md, packages/package_info_plus/README.md, packages/sensors_plus/README.md
Fixed broken links due to recent directory restructuring in plus repo: https://github.com/fluttercommunity/plus_plugins/pull/313.
Changed "#usage" link from pub.dev to Github for `battery_plus`.
=> Fix broken link in READMEs

packages/battery/CHANGELOG.md, packages/battery/README.md, packages/battery/pubspec.yaml, packages/battery/tizen/src/battery_tizen_plugin.cc, packages/battery_plus/CHANGELOG.md, packages/battery_plus/README.md, packages/battery_plus/pubspec.yaml, packages/battery_plus/tizen/src/battery_plus_tizen_plugin.cc, packages/connectivity/CHANGELOG.md, packages/connectivity/README.md, packages/connectivity/pubspec.yaml, packages/connectivity/tizen/src/connectivity_tizen_plugin.cc, packages/sensors/CHANGELOG.md, packages/sensors/README.md, packages/sensors/pubspec.yaml, packages/sensors/tizen/src/sensors_plugin.cc, packages/sensors_plus/CHANGELOG.md, packages/sensors_plus/README.md, packages/sensors_plus/pubspec.yaml, packages/sensors_plus/tizen/src/sensors_plus_plugin.cc, packages/wearable_rotary/CHANGELOG.md, packages/wearable_rotary/README.md, packages/wearable_rotary/pubspec.yaml, packages/wearable_rotary/tizen/src/wearable_rotary_plugin.cc
EventChannels have to be preserved in memory in order to work properly.
I tested modified plugins, no issues occurred.
It fixes #131 
Signed-off-by: Rafal Walczyna <r.walczyna@samsung.com>
=> Keep EventChannel in memory for the lifetime.

packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc
=> [flutter_tts] Manage a speaking state on the state changed callback

packages/permission_handler/example/tizen/tizen-manifest.xml, packages/permission_handler/tizen/project_def.prop, packages/permission_handler/tizen/src/permission_handler_tizen_plugin.cc, packages/permission_handler/tizen/src/permission_manager.cc, packages/permission_handler/tizen/src/permission_manager.h, packages/permission_handler/tizen/src/service_manager.cc, packages/permission_handler/tizen/src/service_manager.h, packages/permission_handler/tizen/src/type.h
* Use ppm_request_permission instead of ppm_request_permissions
* Now the requests are executed sequentially, one by one
=> [permission_handler] Support Tizen 4.0

packages/flutter_tts/CHANGELOG.md, packages/flutter_tts/README.md, packages/flutter_tts/example/integration_test/flutter_tts_test.dart, packages/flutter_tts/pubspec.yaml, packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc
* The implementation of this plugin expects to return a valid value such as 1,0.
So I mimicked other platform implementations.
=> [flutter_tts] Always send valid values instead of Error

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc
Now, This PR only contains PlatformView's Intreface change.
=> [webview_flutter] Apply PlatformView's Intreface

packages/google_maps_flutter/README.md, packages/google_maps_flutter/lib/src/convert.dart, packages/google_maps_flutter/lib/src/google_maps_controller.dart
* Handle CameraUpdate class for AnimateCamera and MoveCamera API
* Note that AnimateCamera API is not supported in Web. Hence, as in
google_maps_flutter_web, it will run the same as MoveCamera API.
=> [google_maps_flutter] Add APIs related to camera property

packages/path_provider/CHANGELOG.md, packages/path_provider/README.md, packages/path_provider/example/integration_test/path_provider_test.dart, packages/path_provider/example/pubspec.yaml, packages/path_provider/example/test_driver/integration_test.dart, packages/path_provider/pubspec.yaml
Changes:
- ~~add missing `permission_handler_tizen` dependency in example~~
- ~~request `mediaLibrary` permission and not `accessMediaLocation` to access Tizen media directories~~
- remove `permission_handler` dependency
- remove test code that depend on `permission_handler`
- migrate test code to null safety
- bump up versions
=> [path_provider] Fix integration test errors and update dependencies 

packages/url_launcher/CHANGELOG.md, packages/url_launcher/README.md, packages/url_launcher/example/integration_test/url_launcher_test.dart, packages/url_launcher/example/lib/main.dart, packages/url_launcher/example/pubspec.yaml, packages/url_launcher/example/test_driver/integration_test.dart, packages/url_launcher/lib/src/app_control.dart, packages/url_launcher/lib/src/types.dart, packages/url_launcher/pubspec.yaml
- Use `get_error_message()` for error message conversion.
- Also minor changes as indicated in the CHANGELOG file. The minimum Dart SDK version has been increased to 2.13.0 to use the new type alias feature.
=> [url_launcher] Use get_error_message() for error message conversion

packages/package_info_plus/example/lib/main.dart, packages/package_info_plus/example/pubspec.yaml, packages/package_info_plus/pubspec.yaml
This PR partially syncs the example code of `package_info_plus_tizen` with that of `package_info_plus` package. This will be released together with the next notable change.
Context: https://github.com/flutter-tizen/plugins/pull/150#discussion_r679875611
=> [package_info_plus] Sync example code with app-facing package 

packages/shared_preferences/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/example/lib/main.dart, packages/shared_preferences/lib/shared_preferences_tizen.dart
Fix memory leaks
- Use Arena to release memory allocated in toNativeUtf8() method.
- Use Arena instead of `malloc()` to release allocated memory automatically. 
- Free `pString` after use it. 
- Fix some styles.
=> [shared_preferences] Fix memory leaks

README.md, packages/webview_flutter/README.md
The webview plugin is not supported on watch devices because
- The implementation doesn't support the Evas GL backend.
- Non-public APIs are used in `liblightweight-web-engine.flutter.so`.
=> [webview_flutter] Update supported devices

tools/commands/build_example.py
* It is unnecessary and does not sync with the output message of subprocess.run
=> Remove unnecessary messages

packages/permission_handler/example/integration_test/permission_handler_test.dart
Opening app settings to view permission status is only allowed in real targets. Specifically, the dependent app `com.samsung.clocksetting.apps` in emulators don't have the required feature.
=> [permission_handler] Allow emulators to pass integration test

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml
=> [webview_flutter] Update lightweight web engine binary

tools/commands/build_example.py, tools/commands/check_tidy.py, tools/commands/command_utils.py, tools/commands/integration_test.py, tools/commands/print_plugins.py, tools/run_command.py
Changes:
- Refactor `run_command.py` and `commands/*.py` to use subparsers for better error handling.
- Make `test_target` an optional parameter to resolve "missing required positional argument" error in `integration_test.py`.
- Use consistent error message in `integration_test.py`.
The last two commits(d470c84f760f5304807f9d5f0658834a35a002c1, 6662780d72eb2d50a9c20360ae02fdc98d4e99eb) are code clean ups. The major changes are in 0c52a49583d7d4abdf627d7a019905f19e1d035a.
=> Refactor tools to use subparsers

packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart, packages/tizen_app_control/example/lib/main.dart, packages/tizen_app_control/lib/app_control.dart
Related to https://github.com/flutter-tizen/engine/pull/185.
Reference: TizenFX's [`AppControl.GetMatchedApplicationIds()`](https://docs.tizen.org/application/dotnet/api/TizenFX/API8/api/Tizen.Applications.AppControl.html#Tizen_Applications_AppControl_GetMatchedApplicationIds_Tizen_Applications_AppControl_)
=> [tizen_app_control] Support getMatchedAppIds

tools/commands/integration_test.py, tools/run_command.py
Sorry for the unexpected huge diff, adding default targets was not as straightforward as I originally thought. I may have done some over refactoring but I already had planned the changes for #230. It was simpler to work with the refactored code so I decided to apply it a bit early.
This PR must be merged after adding the `--platforms` option in `integration_test.yml`.
Summary:
- Run clean command after each test to save disk space. ~~(Nothing has changed between line 136~237)~~
- Don't catch exceptions and print stack trace.
- Fix incorrectly used nested f-string.
- Introduce `Target` which encapsulates a Tizen device.
- Introduce `TargetManager` which finds and manages a collection of `Target`s.
- Update outdated docstrings.
- Define some words used in code, such as `target`, `platform`, …
=> Refactor, run clean command after each test, improve logic for setting default targets.

.github/workflows/build.yml, .github/workflows/integration_test.yml
Github workflows script that runs integration test on pull requests. This PR should be merged after setting up self-hosted runner.
Notes:
- Script doesn't run on forked repositories to silence no self-hosted runner error.
- Currently only a single self-hosted runner runs on the server machine, this may lag CI when multiple commits are submitted to the repo in a short time period. I have a few solutions in mind but need to verify some things first. Anyhow, it will be implemented in the next PR.
- Currently only supports testing on wearable-5.5 emulator.
Testing done on https://github.com/flutter-tizen/plugins/pull/228.
=> Add integration test workflow

packages/video_player/tizen/src/video_player.cc, packages/video_player/tizen/src/video_player.h
When flutter engine upgrade to 2.5.1, only call mark frame available
API can triggle previous frame destruction callback.
#250
=> Fix video player plugin freeze issue

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/example/integration_test/webview_flutter_test.dart, packages/webview_flutter/example/lib/main.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc
**webview_flutter**
- Update  base to ``2.3.0``
#267
=> [webview_flutter] Update webview_flutter (2.3.0) 

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/README.md, packages/google_maps_flutter/example/tizen/tizen-manifest.xml, packages/google_maps_flutter/lib/src/circle.dart, packages/google_maps_flutter/lib/src/google_maps_controller.dart, packages/google_maps_flutter/lib/src/marker.dart, packages/google_maps_flutter/lib/src/polygon.dart, packages/google_maps_flutter/lib/src/polyline.dart, packages/google_maps_flutter/lib/src/util.dart, packages/google_maps_flutter/pubspec.yaml
**google_maps_flutter**
- Replace API 
#267
Needs #269
=>  [google_maps_flutter] Replace deprecated API

analysis_options_plus.yaml, packages/battery_plus/example/pubspec.yaml, packages/battery_plus/pubspec.yaml, packages/connectivity_plus/example/lib/main.dart, packages/connectivity_plus/example/pubspec.yaml, packages/connectivity_plus/pubspec.yaml, packages/device_info_plus/example/lib/main.dart, packages/device_info_plus/example/pubspec.yaml, packages/device_info_plus/pubspec.yaml, packages/network_info_plus/example/pubspec.yaml, packages/network_info_plus/pubspec.yaml, packages/package_info_plus/example/integration_test/package_info_plus_test.dart, packages/package_info_plus/example/lib/main.dart, packages/package_info_plus/example/pubspec.yaml, packages/package_info_plus/pubspec.yaml, packages/sensors_plus/example/lib/main.dart, packages/sensors_plus/example/lib/snake.dart, packages/sensors_plus/example/pubspec.yaml, packages/sensors_plus/pubspec.yaml, packages/share_plus/example/lib/image_previews.dart, packages/share_plus/example/lib/main.dart, packages/share_plus/example/pubspec.yaml, packages/share_plus/pubspec.yaml
Closes #254.
References: 
- https://github.com/fluttercommunity/plus_plugins/pull/519
- https://github.com/fluttercommunity/plus_plugins/pull/537
=> [multi-packages] Migrate plus plugins to use flutter_lints

packages/battery/tizen/src/battery_tizen_plugin.cc, packages/battery_plus/tizen/src/battery_plus_tizen_plugin.cc, packages/camera/tizen/src/camera_device.cc, packages/image_picker/tizen/src/image_resize.h, packages/webview_flutter/tizen/src/webview.cc
Fix following issue:
* Missing break
* Uninitialized field
* Incorrect comparison
=> [multi-packages]  Fix issues from static analysis

packages/flutter_tts/CHANGELOG.md, packages/flutter_tts/README.md, packages/flutter_tts/example/lib/main.dart, packages/flutter_tts/example/pubspec.yaml, packages/flutter_tts/example/tizen/Runner.csproj, packages/flutter_tts/example/tizen/tizen-manifest.xml, packages/flutter_tts/pubspec.yaml, packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc, packages/flutter_tts/tizen/src/text_to_speech.cc, packages/flutter_tts/tizen/src/text_to_speech.h
closes #257.
TODO:
`tts.h` doesn't have apis that can control the tts volume, I could increase the volume with sound manager but I'm looking for something that wouldn't affect other systems. -> tts internally acquire and relinquish focus on voice audio stream.
=> [flutter_tts] Fix bug and support setting speech volume

packages/camera/CHANGELOG.md, packages/camera/README.md, packages/camera/pubspec.yaml, packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h
=> [camera] Fix preview freeze issue

packages/webview_flutter/tizen/src/webview_factory.cc
string literal was used to initialize 'path' variable, but later in code
free() was called for it. It causes releasing memory for non-heap value.
[Verification] Plugin builds properly.
=> [webview_flutter] Fixed memory releasing for non-heap value

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc, packages/webview_flutter/tizen/src/webview_factory.h, packages/webview_flutter/tizen/src/webview_flutter_tizen_plugin.cc
Needs https://github.com/flutter-tizen/engine/pull/212
=> [webview_flutter] Apply PlatformView API changes

packages/integration_test/CHANGELOG.md, packages/integration_test/README.md, packages/integration_test/example/integration_test/example_test.dart, packages/integration_test/example/test_driver/integration_test.dart, packages/integration_test/example/tizen/Runner.csproj, packages/integration_test/example/tizen/tizen-manifest.xml, packages/integration_test/pubspec.yaml, packages/integration_test/tizen/src/integration_test_plugin.cc
It's been 9 months since the last release of this package and we need to publish a new release to apply https://github.com/flutter-tizen/plugins/pull/175 and suppress warnings generated when building other plugins that depend on this package.
=> [integration_test] Version bump to 2.0.1

packages/path_provider/CHANGELOG.md, packages/path_provider/README.md, packages/path_provider/example/integration_test/path_provider_test.dart, packages/path_provider/example/lib/main.dart, packages/path_provider/example/pubspec.yaml, packages/path_provider/example/tizen/Runner.csproj, packages/path_provider/example/tizen/tizen-manifest.xml, packages/path_provider/lib/path_provider_tizen.dart, packages/path_provider/pubspec.yaml, tools/recipe.yaml
`getDownloadsDirectory` has been removed because it is only relevant on desktop platforms. Use `getExternalStorageDirectories` with `StorageDirectory.downloads` as argument instead.
=> [path_provider] Update path_provider to 2.0.7

packages/sensors_plus/CHANGELOG.md, packages/sensors_plus/README.md, packages/sensors_plus/example/lib/main.dart, packages/sensors_plus/example/pubspec.yaml, packages/sensors_plus/example/test_driver/integration_test.dart, packages/sensors_plus/example/tizen/Runner.csproj, packages/sensors_plus/example/tizen/tizen-manifest.xml, packages/sensors_plus/pubspec.yaml, packages/sensors_plus/tizen/src/sensors_plus_plugin.cc
- Set the sampling interval to 60 ms (same as Android's [`SENSOR_DELAY_UI`](https://developer.android.com/guide/topics/sensors/sensors_overview)) because the current 1000 ms is too large.
- Increase the frontend package version to 1.2.1.
- I didn't add support for the newly-added `magnetometerEvents` API because the magnetic sensor is available on none of Tizen devices available in the market.
=> [sensors_plus] Increase the sampling rate

packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/pubspec.yaml, packages/video_player/tizen/src/video_player.cc
- Assign `on_seek_completed_` of player before calling `player_set_play_position` to fix intermittent errors.
If `onSeekCompleted()` is called before `on_seek_completed_` is assigned, uninitialized `on_seek_completed_` can cause serious crash or it is not called at all.
=> [video_player] Fix empty seekCompletedCallback issue

.github/workflows/build.yml
Some APIs are supported from tizen 6.5, and this is a preparation work for them.
=> Add tizen 6.5 environment for ci

packages/messageport/CHANGELOG.md, packages/messageport/README.md, packages/messageport/example/README.md, packages/messageport/example/integration_test/messageport_test.dart, packages/messageport/example/lib/main.dart, packages/messageport/example/pubspec.yaml, packages/messageport/example/test_driver/integration_test.dart, packages/messageport/example/tizen/Runner.csproj, packages/messageport/example/tizen/tizen-manifest.xml, packages/messageport/lib/messageport_tizen.dart, packages/messageport/lib/src/messageport_manager.dart, packages/messageport/pubspec.yaml, packages/messageport/tizen/src/messageport.cc, packages/messageport/tizen/src/messageport.h, packages/messageport/tizen/src/messageport_tizen_plugin.cc
- Add new APIs `LocalPort.create` and `RemotePort.connect` which replace `TizenMessagePort.createLocalPort` and `TizenMessagePort.connectToRemotePort` respectively.
- Minor cleanups.
Part of https://github.com/flutter-tizen/flutter-tizen/pull/303#issuecomment-1001450222.
=> [messageport_tizen] Add LocalPort.create and RemotePort.connect

packages/tizen_app_control/CHANGELOG.md, packages/tizen_app_control/README.md, packages/tizen_app_control/example/lib/main.dart, packages/tizen_app_control/example/pubspec.yaml, packages/tizen_app_control/pubspec.yaml
Upgrade `messageport_tizen` to 0.2.0 in `tizen_app_control` example. If major version starts with 0, the next minor version is not considered a compatiable release so `pub get` will not retrieve 0.2.0 for `^0.1.0`.
Fixes:
```
Exception: The project type of messageport_tizen is "sharedLib" which is not supported.
Make sure the package is up to date by running "flutter-tizen pub upgrade".
If you are the maintainer of the messageport_tizen package, consider migrating the project to "staticLib" type.
Otherwise, you may modify the value of "type" in /home/hakkyu/.pub-cache/hosted/pub.dartlang.org/messageport_tizen-0.1.0/tizen/project_def.prop to temporarily fix the problem.
```
=> [tizen_app_control] Update messageport_tizen dependency in example to fix build error

packages/share_plus/CHANGELOG.md, packages/share_plus/README.md, packages/share_plus/example/pubspec.yaml, packages/share_plus/lib/share_plus_tizen.dart, packages/share_plus/pubspec.yaml
https://github.com/flutter-tizen/plugins/issues/310
Fixes Dart analysis error:
error - share_plus/lib/share_plus_tizen.dart:18:11 - The setter 'disableSharePlatformOverride' isn't defined for the type 'Share'. Try importing the library that defines 'disableSharePlatformOverride', correcting the name to the name of an existing setter, or defining a setter or field named 'disableSharePlatformOverride'. - undefined_setter
=> [share_plus] Remove obsolete registration code

packages/audioplayers/CHANGELOG.md, packages/battery_plus/CHANGELOG.md, packages/camera/CHANGELOG.md, packages/connectivity_plus/CHANGELOG.md, packages/device_info_plus/CHANGELOG.md, packages/flutter_tts/CHANGELOG.md, packages/geolocator/CHANGELOG.md, packages/google_maps_flutter/CHANGELOG.md, packages/image_picker/CHANGELOG.md, packages/integration_test/CHANGELOG.md, packages/messageport/CHANGELOG.md, packages/network_info_plus/CHANGELOG.md, packages/package_info_plus/CHANGELOG.md, packages/path_provider/CHANGELOG.md, packages/permission_handler/CHANGELOG.md, packages/sensors_plus/CHANGELOG.md, packages/share_plus/CHANGELOG.md, packages/shared_preferences/CHANGELOG.md, packages/tizen_app_control/CHANGELOG.md, packages/url_launcher/CHANGELOG.md, packages/video_player/CHANGELOG.md, packages/wakelock/CHANGELOG.md, packages/wearable_rotary/CHANGELOG.md, packages/webview_flutter/CHANGELOG.md
Latest events should always come first. e.g. 
- battery_plus: https://pub.dev/packages/battery_plus/changelog (correct)
- battery_plus_tizen: https://pub.dev/packages/battery_plus_tizen/changelog (wrong)
=> Reverse the order of CHANGELOGs

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/example/pubspec.yaml, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/buffer_pool.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc, packages/webview_flutter/tizen/src/webview_factory.h, packages/webview_flutter/tizen/src/webview_flutter_tizen_plugin.cc
Add missing includes and remove unused includes.
The most important part is the added `Ecore_IMF.h` dependency of `webview.h`. The plugin is not compatible with the updated `flutter_platform_view.h` that I'm currently working on due to the missing include. All occurrences of 
```cpp
#include <flutter/standard_message_codec.h>
```
will be removed after the work is done because they are only required by `flutter_platform_view.h`.
=> [webview_flutter] Organize includes

packages/geolocator/example/pubspec.yaml, packages/permission_handler/example/pubspec.yaml
Substitute `git://` in `example/pubspec.yaml` with the GitHub-supported format `https://`.
Error log:
```
2022-03-16T05:07:41.4281921Z Running "flutter pub get" in geolocator...                       1,110ms
2022-03-16T05:07:42.0932931Z Running "flutter pub get" in example...                         
2022-03-16T05:07:42.0960824Z Git error. Command: `git clone --mirror git://github.com/Baseflow/baseflow_plugin_template.git /opt/hostedtoolcache/flutter/2.10.3-stable/x64/.pub-cache/git/cache/baseflow_plugin_template-4fbabee1114b5508a9ffc49dfff58dc6ce1c5577`
2022-03-16T05:07:42.0966073Z stdout: 
2022-03-16T05:07:42.0969027Z stderr: Cloning into bare repository '/opt/hostedtoolcache/flutter/2.10.3-stable/x64/.pub-cache/git/cache/baseflow_plugin_template-4fbabee1114b5508a9ffc49dfff58dc6ce1c5577' …
```
=> Do not use the git protocol in pubspecs

packages/webview_flutter/tizen/src/buffer_pool.cc, packages/webview_flutter/tizen/src/buffer_pool.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
This is a compromise of partial rendering for performance. A sync issue may occur in the sw backend.
This patch improves rendering which is related to issue 2 of https://github.com/flutter-tizen/plugins/issues/339
=> [webview_flutter] In the case of sw backend, use only one buffer for rendering

tools/lib/src/integration_test_command.dart
Retaining the original semantics of recipe became tricky after depending on `flutter_plugin_tools`. I'll refactor the tool code after looking more into the base classes of `flutter_plugin_tools`, or change the semantics of recipe. For now missing packages in recipe will be skipped.
=> Quick fix for missing package in recipe

packages/battery_plus/tizen/src/battery_plus_tizen_plugin.cc, packages/battery_plus/tizen/src/device_battery.cc, packages/battery_plus/tizen/src/device_battery.h
Part of [the code refactoring project](https://github.com/flutter-tizen/plugins/issues/354).
- Extract the `DeviceBattery` class from `BatteryPlusTizenPlugin` for better separation of the platform channel communication and the device API usage. (I referred to the [battery_plus_windows](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/battery_plus/battery_plus_windows/windows/include/battery_plus_windows/system_battery.h) implementation.)
- Create an enum `BatteryStatus` to indicate the current status of the device battery or an error status.
- `RegisterObserver`/`UnregisterObserver` → `StartListen`/`StopListen`
- `StartListen` takes `BatteryStatusCallback` as an argument.
- Create a new method `GetLevel`.
- Let `GetStatus` (previously `GetBatteryStatus`) return a value …
=> [battery_plus] Refactor the C++ code

packages/connectivity_plus/tizen/src/connection.cc, packages/connectivity_plus/tizen/src/connection.h, packages/connectivity_plus/tizen/src/connectivity_plus_tizen_plugin.cc
Part of [the code refactoring project](https://github.com/flutter-tizen/plugins/issues/354). This change is an analogue of https://github.com/flutter-tizen/plugins/pull/351.
- Extract the `Connection` class from `ConnectivityPlusTizenPlugin` for better separation of the platform channel communication and the device API usage. (I referred to the [connectivity_plus_windows](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus/connectivity_plus_windows/windows/connectivity_plus_windows_plugin.cpp) implementation.)
- Create an enum `ConnectionType` to indicate the current connectivity type or an error status.
- `RegisterObserver`/`ClearObserver` → `StartListen`/`StopListen`
- `StartListen` takes `ConnectionTypeCallback` as an argument.
- Create a new method …
=> [connectivity_plus] Refactor the C++ code

packages/image_picker/tizen/src/image_picker_tizen_plugin.cc, packages/image_picker/tizen/src/image_resize.cc, packages/image_picker/tizen/src/image_resize.h, packages/image_picker/tizen/src/permission_manager.cc, packages/image_picker/tizen/src/permission_manager.h
Part of [the code refactoring project](https://github.com/flutter-tizen/plugins/issues/354).
**image_picker_tizen_plugin.cc**
- Create a class `PermissionManager` as a replacement for `CheckPermissionAndPickContent`.
- The class is a wrapper of the Tizen PPM API and provides two methods: `CheckPermission` and `RequestPermssion`.
- Note that `RequestPermssion` is a blocking method.
- The code will be shared by multiple packages. The `CheckPermission` method is not used by this package but is for use by other packages.
- The return types of the methods are `PermissionStatus` and `PermissionResult` respectively.
- The methods return `kAllow` or `kAllowForever` when compiled for TV.
- Use the `GetValueFromEncodableMap` template function to process method call arguments.
- Remove …
=> [image_picker] Refactor the C++ code

packages/camera/CHANGELOG.md, packages/camera/README.md, packages/camera/pubspec.yaml, packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h
Related to https://github.com/flutter-tizen/engine/pull/259
=> [camera] Apply texture API change

packages/sensors_plus/tizen/src/device_sensor.cc, packages/sensors_plus/tizen/src/device_sensor.h, packages/sensors_plus/tizen/src/sensors_plus_plugin.cc
This PR includes :
* Extract `DeviceSensor` class
* Simplify `SensorsPlusPlugin` Implementation
* Use derived class from `flutter::StreamHandler` to set stream handlers
This change contribute #354
=> [sensors_plus] Refactor the C++ code

packages/battery_plus/CHANGELOG.md, packages/battery_plus/README.md, packages/battery_plus/example/lib/main.dart, packages/battery_plus/example/pubspec.yaml, packages/battery_plus/pubspec.yaml, packages/battery_plus/tizen/src/battery_plus_tizen_plugin.cc
Adds support for `Battery.batteryState`.
Also reverts part of https://github.com/flutter-tizen/plugins/pull/351. The `EventChannel` instance must be preserved in memory during the plugin lifetime. See https://github.com/flutter-tizen/plugins/pull/134.
=> [battery_plus] Implement getBatteryState

packages/google_maps_flutter/example/pubspec.yaml, packages/google_maps_flutter/pubspec.yaml
=> [google_maps_flutter] Update dependency package

.github/recipe.yaml, packages/url_launcher/CHANGELOG.md, packages/url_launcher/README.md, packages/url_launcher/example/integration_test/url_launcher_test.dart, packages/url_launcher/example/lib/main.dart, packages/url_launcher/example/pubspec.yaml, packages/url_launcher/pubspec.yaml
The `launch` API has been deprecated and replaced by `launchUrl`.
https://pub.dev/packages/url_launcher/changelog
=> [url_launcher] Update url_launcher to 6.1.0

packages/connectivity_plus/CHANGELOG.md, packages/connectivity_plus/README.md, packages/connectivity_plus/example/pubspec.yaml, packages/connectivity_plus/pubspec.yaml, packages/connectivity_plus/tizen/src/connection.cc, packages/connectivity_plus/tizen/src/connection.h, packages/connectivity_plus/tizen/src/connectivity_plus_tizen_plugin.cc
Adds support for `ConnectivityResult.bluetooth`.
Also reverts part of https://github.com/flutter-tizen/plugins/pull/352. The `EventChannel` instance must be preserved in memory during the plugin lifetime. See https://github.com/flutter-tizen/plugins/pull/134.
=> [connectivity_plus] Add bluetooth as connectivity result

packages/device_info_plus/tizen/src/device_info_plus_tizen_plugin.cc
Replace `std::vector<std::pair<>>` with `std::map<>`.
Contributes to https://github.com/flutter-tizen/plugins/issues/354.
=> [device_info_plus] Minor code cleanup

packages/video_player/CHANGELOG.md, packages/video_player/tizen/src/message.cc, packages/video_player/tizen/src/message.h, packages/video_player/tizen/src/video_player.cc, packages/video_player/tizen/src/video_player.h, packages/video_player/tizen/src/video_player_error.h, packages/video_player/tizen/src/video_player_options.h, packages/video_player/tizen/src/video_player_tizen_plugin.cc
Just some style fixes. Please see the commit history for details.
- Apply naming rules. See the below note for the exceptions.
- Use a fixed-width integer type `int64_t` instead of `long`.
- Remove unnecessary logs. See the below note for details.
- Remove unused buffering-related callbacks.
Notes:
- The types and methods in `message.h` are expected to be auto-generated from [the common interface definition](https://github.com/flutter/plugins/blob/main/packages/video_player/video_player_android/pigeons/messages.dart) and thus do not follow the language-specific naming convention.
- Not all debug logs have been removed because they can be useful for later debugging. I removed only redundant logs that do not carry extra information.
- This plugin does not follow the error code format in …
=> [video_player] Minor code cleanup

tools/lib/src/integration_test_command.dart, tools/lib/src/recipe.dart, tools/test/device_test.dart, tools/test/integration_test_command_test.dart, tools/test/recipe_test.dart
Follows the original semantics of recipe:
- plugins not in the recipe file are not recognized by the tool during integration test.
- plugins with empty list are marked 'excluded' during integration test.
=> Implement recipe logic properly

tools/lib/src/integration_test_command.dart
This PR runs the `flutter-tizen precache --tizen` command before the actual integration-test step so that artifact fetching time doesn't drain out the timeout limit of tests.
=> Precache tizen artifacts before test runs

packages/sqflite/tizen/src/database_manager.h, packages/webview_flutter/tizen/src/webview.cc
Fixed warnings:
* not initialized database_ pointer
* dereference without checking null
=> Fixed warnings found with static analysis tool

.github/labeler.yml, packages/integration_test/example/integration_test/example_test.dart, packages/sqflite/example/lib/main.dart, packages/sqflite/example/lib/manual_test_page.dart, packages/sqflite/example/lib/model/item.dart, packages/sqflite/example/lib/open_test_page.dart, packages/sqflite/example/lib/src/item_widget.dart, packages/sqflite/example/lib/src/main_item_widget.dart, packages/sqflite/example/lib/test_page.dart, packages/sqflite/example/lib/type_test_page.dart, packages/sqflite/example/pubspec.yaml, packages/webview_flutter/lib/src/platform_view_tizen.dart
Also add missing sqflite label to `labeler.yaml`
=> Fix dart analyze issues

README.md, packages/permission_handler/CHANGELOG.md, packages/permission_handler/tizen/src/app_settings_manager.cc, packages/permission_handler/tizen/src/app_settings_manager.h, packages/permission_handler/tizen/src/permission_handler_tizen_plugin.cc, packages/permission_handler/tizen/src/permission_manager.cc, packages/permission_handler/tizen/src/permission_manager.h, packages/permission_handler/tizen/src/permissions.h, packages/permission_handler/tizen/src/service_manager.cc, packages/permission_handler/tizen/src/service_manager.h
Part of [the code refactoring project](https://github.com/flutter-tizen/plugins/issues/354).
`app_settings_manager.cc`:
- Remove the `AppPermissions` class and move its logic to `AppSettingsManager::OpenAppSettings`. The class has been first introduced in #142, but adds unnecessary complexity to the code.
- Replace the `PackageName` class with a simple function `GetPackageName`.
`permission_handler_tizen_plugin.cc` & `permission_manager.cc`:
- The code has almost been rewritten from scratch (reduced 200~ lines of code).
- The `PermissionManager` class is a copy of image_picker_tizen's `PermissionManager`. (See https://github.com/flutter-tizen/plugins/pull/353.)
- The only difference is that `PermissionStatus` and `PermissionResult` are now a single type, in accordance with the type …
=> [permission_handler] Refactor the C++ code

.github/workflows/build.yml
- Increase the Tizen Studio version to 4.6.
- Skip installing unnecessary dependencies.
- Revert https://github.com/flutter-tizen/plugins/pull/315.
- Change the certificate profile name to `tizen` to avoid any confusion.
Using the latest Tizen Studio reduces the total build time because there's no need to install updates.
=> Update Tizen Studio to 4.6

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/tizen/src/buffer_pool.cc, packages/webview_flutter/tizen/src/buffer_pool.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc, packages/webview_flutter/tizen/src/webview_factory.h, packages/webview_flutter/tizen/src/webview_flutter_tizen_plugin.cc
Part of [the code refactoring project](https://github.com/flutter-tizen/plugins/issues/354).
`BufferUnit` and `BufferPool`:
- Use in-class initializers (instead of initializer list in the constructor) for constant values.
- Remove unused `BufferUnit::Index`.
- Inline simple accessor functions (`BufferUnit::IsUsed` and `BufferUnit::GpuBuffer`).
`WebView`:
- Change the type of `params` (constructor argument) to `EncodableValue` to reuse the `GetValueFromEncodableMap` function.
- Never throw exceptions that are not explicitly handled in their call trees.
- Rename `RequestErrorType` to `ResourceErrorType`.
- Rename `NeedsSwBackend` to `IsRunningOnEmulator`.
- Make `texture_variant_` a unique pointer.
- Make `HandleMethodCall` always send a result. (Fixes …
=> [webview_flutter] Refactor the C++ code

.github/labeler.yml, .github/workflows/release.yml, tools/lib/src/main.dart, tools/lib/src/process_runner_apis.dart, tools/lib/src/publish_plugin_command.dart, tools/pubspec.yaml
Closes #378.
1. Checks for packages where version field in `pubspec.yaml` changed.
2. Run `pub publish --dry-run` to make CI fail on any errors or warnings. For example, missing a corresponding version entry in `CHANGELOG.md`.
1. Hold off completing `release` workflow until all other workflows are finished.
2. Run `pub publish --dry-run` again just in case.
3. Publish the changed packages identified in the pushed PR.
The content of the `credential.json`, which is created when running `dart pub login`, must be added to [Github repository secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) with name "PUB_CREDENTIALS". 
New packages must be published manually because pub.dev current doesn't support publishing a new …
=> Publish packages automatically after merge

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
=> [webview_flutter] Apply PlatformView API change

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc
* Perform go back when back key pressed if navigation stack has a item.
if not, the app will be terminated by the engine.
=> [webview_flutter] Handle back key

packages/tizen_app_control/CHANGELOG.md, packages/tizen_app_control/README.md, packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart, packages/tizen_app_control/example/lib/main.dart, packages/tizen_app_control/example/pubspec.yaml, packages/tizen_app_control/lib/app_control.dart, packages/tizen_app_control/lib/app_manager.dart, packages/tizen_app_control/lib/src/ffi.dart, packages/tizen_app_control/lib/tizen_app_control.dart, packages/tizen_app_control/pubspec.yaml
Please see the CHANGELOG for details.
tizen_app_manager 0.1.1 (https://github.com/flutter-tizen/plugins/commit/b0ad4c96c65484755412ca94a045604e95c3e1d8) must be released first for the CI to pass. @HakkyuKim Could you check the integration test server?
=> [tizen_app_control] Deprecate AppManager

packages/tizen_app_manager/CHANGELOG.md, packages/tizen_app_manager/README.md, packages/tizen_app_manager/example/lib/main.dart, packages/tizen_app_manager/lib/app_manager.dart, packages/tizen_app_manager/pubspec.yaml
* Implement a Dart finalizer for `AppRunningContext`.
* Deprecate `AppRunningContext.dispose`.
* Clean up README.
When an `AppRunningContext` object goes out of scope, the platform resource (`AppContext`) associated with it is now automatically released by the garbage collector.
=> [tizen_app_manager] Deprecate AppRunningContext.dispose

packages/battery_plus/tizen/inc/battery_plus_tizen_plugin.h, packages/geolocator/tizen/inc/geolocator_tizen_plugin.h, packages/messageport/tizen/inc/messageport_tizen_plugin.h, packages/tizen_app_manager/tizen/inc/tizen_app_manager_plugin.h, packages/tizen_audio_manager/tizen/inc/tizen_audio_manager_plugin.h, packages/tizen_audio_manager/tizen/src/log.h, packages/tizen_package_manager/tizen/inc/tizen_package_manager_plugin.h
In some packages, the automatically generated file has a license.
Removed for consistency with other packages.
=> Clean up license in auto-generated file

packages/flutter_tts/CHANGELOG.md, packages/flutter_tts/pubspec.yaml, packages/flutter_tts/tizen/inc/flutter_tts_tizen_plugin.h, packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc, packages/flutter_tts/tizen/src/text_to_speech.cc, packages/flutter_tts/tizen/src/text_to_speech.h
Part of [the code refactoring project.](https://github.com/flutter-tizen/plugins/issues/354)
- Extract method.
- Hiding tizen api in plugin.cc
- Minimize use of output parameters
- Change method name(Init-> TtsCreate, DeInit -> TtsDestroy, ...)
=> [flutter_tts] Refactor the C++ code

packages/flutter_tts/CHANGELOG.md, packages/flutter_tts/README.md, packages/flutter_tts/example/lib/main.dart, packages/flutter_tts/example/pubspec.yaml, packages/flutter_tts/pubspec.yaml, packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc, packages/flutter_tts/tizen/src/text_to_speech.cc, packages/flutter_tts/tizen/src/text_to_speech.h
- Let `setSpeechRate` compute the speech speed (between min-max) based on the given [normalized](https://github.com/dlutton/flutter_tts/blob/112b9317dd0397324cb1d8e4126cd772d583229b/lib/flutter_tts.dart#L171) speech rate (0-1).
- Unsupport `getSpeechRateValidRange` which returns an invalid `platform` value ("android") on Tizen.
- Update flutter_tts to 3.5.0 and update the example app.
- Some code refactoring.
- Remove the unused TTS error callback.
- Let `SetStateChanagedCallback` return values of type `TtsState`.
- Simplify comments.
- Let `HandleAwaitSpeakCompletion` take an argument of type `EncodableValue` for consistency.
- Inline `OnStateChanged`and `OnUtteranceCompleted` into relevant callbacks.
Previous discussion: https://github.com/flutter-tizen/plugins/pull/401#issuecomment-1173 …
=> [flutter_tts] Make speech speed proportional to speech rate

.github/recipe.yaml, packages/google_sign_in/CHANGELOG.md, packages/google_sign_in/README.md, packages/google_sign_in/example/integration_test/secure_storage_test.dart, packages/google_sign_in/example/pubspec.yaml, packages/google_sign_in/lib/google_sign_in_tizen.dart, packages/google_sign_in/lib/src/secure_storage.dart, packages/google_sign_in/pubspec.yaml, packages/google_sign_in/tizen/.gitignore, packages/google_sign_in/tizen/inc/google_sign_in_tizen_plugin.h, packages/google_sign_in/tizen/project_def.prop, packages/google_sign_in/tizen/src/google_sign_in_tizen_plugin.cc, packages/google_sign_in/tizen/src/log.h, packages/google_sign_in/tizen/src/secure_storage.cc, packages/google_sign_in/tizen/src/secure_storage.h
Authorization token is saved on disk, users don't have to request new authorization between app sessions unless user has explicitly signed out from the app.
- Used [KeyManager](https://docs.tizen.org/application/native/guides/security/secure-key/) API which supports data encryption with various cipher algorithms.
- Decision on encryption algorithm and mode is based on Android's implementation of [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) and [relevant issue](https://github.com/mogol/flutter_secure_storage/issues/69), though it's not entirely same due to API limitation.
=> [google_sign_in] Persist token on disk

packages/path_provider/CHANGELOG.md, packages/path_provider/README.md, packages/path_provider/pubspec.yaml, packages/shared_preferences/CHANGELOG.md, packages/shared_preferences/README.md, packages/shared_preferences/pubspec.yaml, packages/tizen_app_control/CHANGELOG.md, packages/tizen_app_control/README.md, packages/tizen_app_control/pubspec.yaml, packages/tizen_app_manager/CHANGELOG.md, packages/tizen_app_manager/README.md, packages/tizen_app_manager/pubspec.yaml, packages/tizen_log/CHANGELOG.md, packages/tizen_log/README.md, packages/tizen_log/pubspec.yaml
This helps resolving dependencies of apps that have ffi ^2.0.0 as a dependency. We may drop support for ffi ^1.1.2 and only support ^2.0.0 in the future.
=> Bump ffi dependencies

packages/camera/CHANGELOG.md, packages/camera/README.md, packages/camera/pubspec.yaml, packages/camera/tizen/src/camera_device.cc, packages/camera/tizen/src/camera_device.h, packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/pubspec.yaml, packages/video_player/tizen/src/video_player.cc, packages/video_player/tizen/src/video_player.h, packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/buffer_pool.cc, packages/webview_flutter/tizen/src/buffer_pool.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
* Resolves flutter-tizen/engine/issues/285.
* This change depends on flutter-tizen/engine/pull/338.
=> Apply new texture APIs

.github/workflows/build.yml, packages/geolocator/CHANGELOG.md, packages/geolocator/README.md, packages/geolocator/example/pubspec.yaml, packages/geolocator/pubspec.yaml, packages/permission_handler/CHANGELOG.md, packages/permission_handler/README.md, packages/permission_handler/example/pubspec.yaml, packages/permission_handler/pubspec.yaml
New versions of `geolocator` and `permission_handler` must be released as `baseflow_plugin_template` dependency was fixed to a specific version.
=> Reallow CI build of geolocator and permission_handler

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/project_def.prop
Based on https://github.com/flutter-tizen/flutter-tizen/pull/407.
With this change, the webview plugin will not be included in `libflutter_plugins.so` and instead `libwebview_flutter_tizen_plugin.so` will be generated and included in a TPK.
@flutter-tizen/maintainers The experimental "implicit user library linking" support for "staticLib" type plugins will be removed in the future. Please migrate to the "sharedLib" type if you have inhouse (or work-in-progress) plugins that use such an old configuration by referring to this change.
=> [webview_flutter] Change the project type to sharedLib

packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/pubspec.yaml, packages/video_player/tizen/src/video_player.cc, packages/video_player/tizen/src/video_player.h
For fixing frame tearing issue on RB5:
1.Should destory media packet in sequence.
2.Should not destory current rendering packet when rendering finished.
=> [video_player] Add a queue for storing decoded media packets

packages/tizen_app_control/CHANGELOG.md, packages/tizen_app_control/example/tizen/.gitignore, packages/tizen_app_control/example/tizen/ui/.gitignore, packages/tizen_app_control/lib/src/ffi.dart
- Remove unused `AppContext`-related typedefs and references, which are a leftover from https://github.com/flutter-tizen/plugins/pull/407.
- Simplify `AttachAppControl` based on Dart 2.15's new `Bool` type support.
- Update `.gitignore` files according to the latest multi-app template.
=> [tizen_app_control] Remove unused code

analysis_options.yaml, packages/camera/example/lib/main.dart, packages/google_maps_flutter/example/integration_test/google_maps_test.dart, packages/google_maps_flutter/example/lib/map_click.dart, packages/google_maps_flutter/example/lib/map_coordinates.dart, packages/google_maps_flutter/example/lib/map_ui.dart, packages/google_maps_flutter/example/lib/padding.dart, packages/google_maps_flutter/example/lib/place_marker.dart, packages/google_maps_flutter/example/lib/tile_overlay.dart, packages/messageport/example/lib/main.dart, packages/path_provider/example/integration_test/path_provider_test.dart, packages/tizen_app_manager/example/lib/main.dart, packages/tizen_audio_manager/example/lib/main.dart, packages/video_player/example/integration_test/video_player_test.dart, packages/video_player/example/lib/main.dart, packages/wearable_rotary/example/lib/custom_page_view.dart, tools/lib/src/main.dart
- Sync the latest flutter/plugins [analysis_options.yaml](https://github.com/flutter/plugins/blob/main/analysis_options.yaml). The following two options were added:
- `avoid_redundant_argument_values` (https://github.com/flutter/plugins/commit/cda37d5640f9fe1d4b1bac9a6e610d5ca4e867ee)
- `use_named_constants` (https://github.com/flutter/plugins/commit/b77f6fcfbf8d02cdf43326a7f9b042bf8916bd36)
- Add the `analyze` command to the tools. To run `flutter analyze` for all packages, run:<p>
```sh
../tools/tools_runner.sh analyze --custom-analysis audioplayers,battery_plus,connectivity_plus,device_info_plus,flutter_tts,geolocator,network_info_plus,package_info_plus,permission_handler,sensors_plus,sqflite,wakelock
```
=> Sync analysis_options.yaml

packages/tizen_bundle/README.md
The dispose() method was removed during the review. 
This PR removes contents related to the dispose() method from the README.md file.
Signed-off-by: Hwankyu Jhun <h.jhun@samsung.com>
=> [tizen_bundle] Update README

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/project_def.prop
Fixes runtime errors of plugins that depend on the webview_flutter plugin (such as google_maps_flutter).
=> [webview_flutter] Set runtime path to $ORIGIN

packages/battery_plus/CHANGELOG.md, packages/battery_plus/README.md, packages/battery_plus/pubspec.yaml, packages/battery_plus/tizen/src/battery_plus_tizen_plugin.cc, packages/connectivity_plus/CHANGELOG.md, packages/connectivity_plus/README.md, packages/connectivity_plus/pubspec.yaml, packages/connectivity_plus/tizen/src/connectivity_plus_tizen_plugin.cc, packages/geolocator/CHANGELOG.md, packages/geolocator/README.md, packages/geolocator/pubspec.yaml, packages/geolocator/tizen/src/geolocator_tizen_plugin.cc, packages/sensors_plus/CHANGELOG.md, packages/sensors_plus/README.md, packages/sensors_plus/pubspec.yaml, packages/sensors_plus/tizen/src/sensors_plus_plugin.cc
* Use a derived class to hold memory not guaranteed by StreamHandlerError.
* This patch prevents crashes caused by dereferences to invalid memory.
* Update version.
=> Hold memory of StreamHandlerError's member

packages/tizen_app_manager/CHANGELOG.md, packages/tizen_app_manager/README.md, packages/tizen_app_manager/example/lib/main.dart, packages/tizen_app_manager/pubspec.yaml, packages/tizen_app_manager/tizen/src/tizen_app_manager_plugin.cc
- Clean up the example app code so that it becomes easier to understand.
- Fix `SetAppTerminateHandler` not being called in `AppContextStreamHandler::OnCancelInternal`.
=> [tizen_app_manager] Revise the example app

packages/wearable_rotary/CHANGELOG.md, packages/wearable_rotary/tizen/src/wearable_rotary_plugin.cc
This patch includes:
* Simplify WearableRotaryPlugin Implementation.
* Use derived class from flutter::StreamHandler to set stream handlers.
* Use derived class from flutter::StreamHandlerError to hold references safely.
This change contribute #354
=> [wearable_rotary] Refactor the C++ code

packages/tizen_bundle/CHANGELOG.md, packages/tizen_bundle/README.md, packages/tizen_bundle/example/integration_test/bundle_test.dart, packages/tizen_bundle/example/lib/main.dart, packages/tizen_bundle/lib/tizen_bundle.dart, packages/tizen_bundle/pubspec.yaml
- Update outdated information in README.
- Remove redundant test cases.
- Simplify the example app.
- Export the `Uint8List` type from `tizen_bundle.dart`.
- Compute `Bundle.length`, `Bundle.isEmpty`, and `Bundle.isNotEmpty` more efficiently.
- Code formatting and cleanups.
=> [tizen_bundle] General cleanups

packages/image_picker/CHANGELOG.md, packages/image_picker/README.md, packages/image_picker/example/lib/main.dart, packages/image_picker/example/pubspec.yaml, packages/image_picker/pubspec.yaml
The return type of `pickMultiImage` is now non-nullable.
Fixes [this CI analysis failure](https://github.com/flutter-tizen/plugins/actions/runs/3203312940/jobs/5233258312).
=> [image_picker] Resolve unnecessary_nullable_for_final_variable_declarations

packages/network_info_plus/CHANGELOG.md, packages/network_info_plus/README.md, packages/network_info_plus/example/integration_test/network_info_plus_test.dart, packages/network_info_plus/example/lib/main.dart, packages/network_info_plus/example/pubspec.yaml, packages/network_info_plus/pubspec.yaml
Update the example app and integration_test to not use iOS-specific permission methods (deprecated as of network_info_plus 2.3.2).
Fixes CI analyze failures.
=> [network_info_plus] Do not use deprecated APIs

.github/workflows/analyze.yml
Use the `tools_runner.sh analyze` command instead of `dart analyze` for analyzing Dart source code, to ensure that `dart pub get` is run for all example apps before the analysis.
c.f. This change is for the "analyze" workflow. f065d1f6658cb35ad824c1160b52cec24787b72c is for the "build" workflow.
Resolves the analyze error of https://github.com/flutter-tizen/plugins/pull/438.
=> Use the tools analyze command for code analysis

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/example/integration_test/google_maps_test.dart
* Map generation callback is an asynchronous call, so a completeer is required.
* This patch fixes test failures that occur on the device while testing.
=> [google_maps_flutter] Use completer to get map id

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/pubspec.yaml
* This plugin still depends on a lightweight web engine.
=> [google_maps_flutter] Change dependency to webview_flutter_lwe

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc
For EncodableValue(), the result of Eina_bool type must be explicitly changed to bool type.
[Log]
```
E/ConsoleMessage(24058): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'int' is not a subtype of type 'bool?' in type cast
E/ConsoleMessage(24058): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:41)
E/ConsoleMessage(24058): <asynchronous suspension>
E/ConsoleMessage(24058): #1      NavigationControls.build.<anonymous closure>.<anonymous closure> (package:webview_flutter_tizen_example/main.dart:462:27)
E/ConsoleMessage(24058): <asynchronous suspension>
```
Eina_Bool documents
`https://docs.tizen.org/application/native/api/wearable/5.5/group__Eina__Types__Group.html#ga3fe0caf72e93b1bab1ca8ee3ccf3f226`
=> [webview_flutter] Fix canGoBack/Forward error

.github/recipe.yaml, .github/workflows/build.yml, packages/permission_handler/example/integration_test/permission_handler_test.dart, tools/lib/src/device.dart, tools/lib/src/integration_test_command.dart
Disable permission popups when testing on a wearable emulator, by creating the `askuser_disable` file. This enables testing of `path_provider_tizen` and `permission_handler_tizen`, but not `geolocator_tizen` because the location service is not available on emulator.
=> Disable permission popups during testing

packages/webview_flutter/tizen/src/webview.cc
ewk_settings_viewport_meta_tag_set() was moved to ewk_settings_product.h in tizen 6.5.
Since this header is non-public, we can no longer use this api.
By default, the viewport meta tag is enabled on mobile and wearable, but it is disabled on TV.
Since webview_flutter_tizen only support the TV profile, it doesn't matter if we don't use this API.
=> [webview_flutter] Remove non-public API

packages/webview_flutter/tizen/src/webview.cc
result_value parameter of Ewk_View_Script_Execute_Cb can be null.
So, add a null check to prevent crashes.
=> [webview_flutter] Prevent invalid access

tools/lib/src/device.dart, tools/lib/src/integration_test_command.dart
Tests may temporarily fail for unknown reason on a self-hosted runner. Try again by passing the verbose (`-v`) option so that the false alarm does not disrupt the subsequent (release) workflow.
=> Run integration test once again on temporary failure

.github/workflows/release.yml, tools/LICENSE, tools/lib/src/device.dart, tools/lib/src/integration_test_command.dart, tools/lib/src/main.dart, tools/lib/src/process_runner_apis.dart, tools/lib/src/publish_command.dart, tools/lib/src/recipe.dart, tools/lib/src/tizen_sdk.dart, tools/pubspec.yaml, tools/test/device_test.dart, tools/test/integration/device_test.dart
- Remove the `debug` parameter from `Device.runIntegrationTest` which has recently been added by https://github.com/flutter-tizen/plugins/pull/497.
- Remove `Device`'s dependency on `package_looping_command.dart` by changing the return type of `Device.runIntegrationTest`.
- Rename `publish_plugin_command.dart` to `publish_command.dart` and replace some occurrences of `plugin` with `package` (see https://github.com/flutter/plugins/pull/6503).
- Update flutter_plugin_tools to 0.13.0 and remove unused dependencies.
- Minor cleanups, including typo fix and etc.
=> Clean up the tool code

packages/google_maps_flutter/example/tizen/tizen-manifest.xml, packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/example/tizen/tizen-manifest.xml, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/project_def.prop, packages/webview_flutter/tizen/src/ewk_internal_api_binding.cc, packages/webview_flutter/tizen/src/ewk_internal_api_binding.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h, packages/webview_flutter/tizen/src/webview_factory.cc, packages/webview_flutter/tizen/src/webview_factory.h, packages/webview_flutter_lwe/example/tizen/tizen-manifest.xml, packages/webview_flutter_lwe/pubspec.yaml, packages/webview_flutter_lwe/tizen/src/webview.cc
- Change the project type to staticLib.
- Enable back key navigation.
- Implement `WebSettings.javascriptMode` and `WebViewController.clearCache`.
- Redirect console messages to stdout/stderr for easy debugging.
- Minor code cleanups.
=> [webview_flutter] General improvements

packages/camera/tizen/src/permission_manager.cc
* TV does not support the privilege API, which causes a crash.
* This patch resolves this crash. but it still doesn't support TV.
=> [camera] Treat permission request as a success on TV

packages/tizen_rpc_port/CHANGELOG.md, packages/tizen_rpc_port/README.md, packages/tizen_rpc_port/example/client/lib/main.dart, packages/tizen_rpc_port/example/server/lib/main.dart, packages/tizen_rpc_port/lib/src/stub_base.dart, packages/tizen_rpc_port/pubspec.yaml
Part of https://github.com/flutter-tizen/plugins/issues/504.
Calling `StubBase.close` will destroy the underlying native handle so no additional operation can be made to the stub afterwards.
=> [tizen_rpc_port] Support explicitly stopping a server

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter_lwe/CHANGELOG.md, packages/webview_flutter_lwe/example/pubspec.yaml, packages/webview_flutter_lwe/tizen/src/webview.cc
`std::to_string(error_code)` shouldn't be used because the error type string is converted back to a Dart enum in [this way](https://github.com/flutter/plugins/blob/webview_flutter_platform_interface-v1.9.5/packages/webview_flutter/webview_flutter_platform_interface/lib/src/method_channel/webview_method_channel.dart#L67-L70). Otherwise a `StateError` occurs.
=> [webview_flutter] Use only error types known to Dart

packages/tizen_package_manager/CHANGELOG.md, packages/tizen_package_manager/README.md, packages/tizen_package_manager/example/lib/main.dart, packages/tizen_package_manager/pubspec.yaml, packages/tizen_package_manager/tizen/src/tizen_package_manager_plugin.cc
Calling `PackageManager.getPackagesInfo` makes the app become unresponsive (for up to 10 seconds) on wearable devices.
=> [tizen_package_manager] Add threading to prevent app freezing

packages/firebase_core/CHANGELOG.md, packages/firebase_core/README.md, packages/firebase_core/pubspec.yaml, packages/url_launcher/CHANGELOG.md, packages/url_launcher/README.md, packages/url_launcher/pubspec.yaml, packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter_lwe/CHANGELOG.md, packages/webview_flutter_lwe/README.md, packages/webview_flutter_lwe/pubspec.yaml
The current version of `url_launcher_tizen` (2.1.1) is causing a dependency resolution failure because it hasn't been published for a while after updating the `tizen_app_control` dependency. Let's publish the package.
```sh
Because url_launcher_tizen <2.0.0 depends on ffi ^0.1.3 and url_launcher_tizen >=2.0.0 <2.0.1 depends on ffi ^1.0.0, url_launcher_tizen <2.0.1 requires ffi ^0.1.3
or ^1.0.0.
And because url_launcher_tizen >=2.0.1 <2.1.0 depends on ffi ^1.1.2 and url_launcher_tizen >=2.1.0 <2.1.1 depends on tizen_app_control ^0.1.0, url_launcher_tizen
<2.1.1 requires tizen_app_control ^0.1.0 or ffi ^0.1.3 or >=1.0.0 <2.0.0.
And because url_launcher_tizen >=2.1.1 depends on tizen_app_control ^0.1.1 which depends on ffi ^1.1.2, every version of url_launcher_tizen requires ffi ^0.1.3 or …
```
=> Publish unreleased changes

tools/lib/src/device.dart, tools/test/device_test.dart
The log output format is different when running on GitHub Actions.
Local:
```sh
✓ Built build/tizen/tpk/org.tizen.messageport_tizen_example-1.0.0.tpk (28.0MB).
00:32 +0: loading /tmp/flutter_tools.VDWCKB/WLUBMS/messageport_test.dart                                                                                           I00:36 +0: loading /tmp/flutter_tools.VDWCKB/WLUBMS/messageport_test.dart                                                                                       3.2s
00:40 +13: All tests passed!
(or)
00:47 +12 -1: Some tests failed.
```
GitHub Actions:
```sh
...
::group::✅ Types test list
::endgroup::
::group::✅ Types test map
::endgroup::
🎉 13 tests passed.
(or)
::error::12 tests passed, 1 failed.
```
See https://github.com/dart-lang/test/tree/master/pkgs/test#selecting-a- …
=> Fix integration test log parsing when running on the CI

packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/pubspec.yaml
Clarify that TV emulator is not supported.
Closes https://github.com/flutter-tizen/plugins/issues/533.
=> [video_player] Add supported devices information to README

.github/recipe.yaml
The test runner hangs right after launching the google_maps_flutter_tizen integration test. The problem is reproducible on any device. The exact cause is unknown. So we temporarily exclude the package from the test recipe to unblock the CI.
=> [ci] Temporarily exclude google_maps_flutter from integration test

tools/lib/src/integration_test_command.dart
The integration test workflow often fails due to `flutter-tizen precache` failure. We need more information (log output) to diagnose the problem.
Example of failed run: https://github.com/flutter-tizen/plugins/actions/runs/4361105042/jobs/7624679581
=> [tool] Log standard error on precache failure

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/example/integration_test/webview_flutter_test.dart, packages/webview_flutter/example/lib/main.dart, packages/webview_flutter/example/pubspec.yaml, packages/webview_flutter/lib/src/tizen_webview.dart, packages/webview_flutter/lib/src/tizen_webview_controller.dart, packages/webview_flutter/lib/src/tizen_webview_cookie_manager.dart, packages/webview_flutter/lib/src/tizen_webview_platform.dart, packages/webview_flutter/lib/webview_flutter_tizen.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
Apply the changed interface from webview_flutter v4.0.2.
Other platforms use pigeon to create APIs and call the associated native APIs.
webview_flutter_tizen support the new interface while maintaining the existing method channel calls.
This change minimize changes to the tizen code in webview.cc while keeping method channel.
=> [webview_flutter] Update webview_flutter_tizen to v0.7.0

analysis_options.yaml, packages/camera/example/lib/main.dart, packages/camera/lib/camera_tizen.dart, packages/camera/lib/src/utils.dart, packages/google_maps_flutter/lib/src/convert.dart, packages/google_maps_flutter/lib/src/google_maps_controller.dart, packages/google_sign_in/example/lib/main.dart, packages/image_picker/example/lib/main.dart, packages/messageport/example/lib/main.dart, packages/path_provider/lib/path_provider_tizen.dart, packages/shared_preferences/example/lib/main.dart, packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart, packages/tizen_app_control/example/lib/main.dart, packages/tizen_app_control/lib/src/app_control.dart, packages/tizen_app_manager/lib/src/app_manager.dart, packages/tizen_package_manager/lib/tizen_package_manager.dart, packages/tizen_rpc_port/example/client/lib/message_client.dart, packages/tizen_rpc_port/example/server/lib/message_server.dart, packages/tizen_rpc_port/lib/src/proxy_base.dart, packages/tizen_rpc_port/lib/src/stub_base.dart, packages/url_launcher/example/lib/main.dart, packages/webview_flutter/lib/src/tizen_webview.dart, packages/webview_flutter/lib/src/tizen_webview_controller.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter_lwe/example/lib/main.dart, tools/analysis_options.yaml, tools/pubspec.yaml
This is a continuation of https://github.com/flutter-tizen/plugins/pull/541. The `analysis_options.yaml` in this repo will exactly match the `analysis_options.yaml` in [flutter/packages](https://github.com/flutter/packages) after this change.
Related commits:
- https://github.com/flutter/plugins/commit/9fdc899b72cac49a4ffade799563c4730c0279a8
- https://github.com/flutter/plugins/commit/783ce6d8f05ecb4da19b90bea063fff5278b551f
- https://github.com/flutter/plugins/commit/1e5efd144f93f3f5b5f804272c126af3185fd2f6
=> More analysis_options alignment

packages/flutter_webrtc/CHANGELOG.md, packages/flutter_webrtc/README.md, packages/flutter_webrtc/example/flutter_webrtc_demo/pubspec.yaml, packages/flutter_webrtc/example/flutter_webrtc_example/pubspec.yaml, packages/flutter_webrtc/pubspec.yaml, packages/flutter_webrtc/tizen/inc/flutter_peerconnection.h, packages/flutter_webrtc/tizen/src/flutter_common.cc, packages/flutter_webrtc/tizen/src/flutter_media_stream.cc, packages/flutter_webrtc/tizen/src/flutter_peerconnection.cc, packages/flutter_webrtc/tizen/src/flutter_video_renderer.cc, packages/flutter_webrtc/tizen/src/flutter_webrtc.cc, packages/flutter_webrtc/tizen/src/flutter_webrtc_base.cc, packages/flutter_webrtc/tizen/third_party/libwebrtc/include/rtc_desktop_capturer.h, packages/flutter_webrtc/tizen/third_party/libwebrtc/include/rtc_peerconnection_factory.h, packages/flutter_webrtc/tizen/third_party/libwebrtc/include/rtc_rtp_capabilities.h, packages/flutter_webrtc/tizen/third_party/libwebrtc/include/rtc_rtp_parameters.h, packages/flutter_webrtc/tizen/third_party/libwebrtc/include/rtc_rtp_transceiver.h
1. Upgrade to [0.9.23](https://github.com/flutter-webrtc/flutter-webrtc)
2. Fix coredump issue #524
=> [flutter_webrtc] Update flutter_webrtc to 0.9.23

packages/messageport/CHANGELOG.md, packages/messageport/example/integration_test/messageport_test.dart, packages/messageport/example/lib/main.dart, packages/messageport/example/pubspec.yaml, packages/messageport/lib/messageport_tizen.dart, packages/messageport/lib/src/messageport_manager.dart, packages/messageport/pubspec.yaml, packages/messageport/tizen/src/messageport.cc, packages/messageport/tizen/src/messageport.h, packages/messageport/tizen/src/messageport_tizen_plugin.cc
- Remove the deprecated class `TizenMessagePort`.
- Various code cleanups.
- Simplify the example app code.
- [Dart] Rename the `TizenMessagePortManager` class to `MessagePortManager`.
- [C++] Add missing includes.
- [C++] Add an error callback for more explicit error handling.
=> [messageport] Remove deprecated APIs

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/integration_test/webview_flutter_test.dart, packages/webview_flutter/lib/src/tizen_webview_controller.dart, packages/webview_flutter/tizen/src/webview.cc
- Remove unnecessary integration test.
- "loadRequest with headers"
- Currently, requests with headers are not supported.
- "Video playback policy", "Audio playback policy"
- Doesn't work normally. (When there are multimedia elements, onPageFinished is not called from the ewk.)
- "target _blank opens in same window"
- Tizen ewk is not supported.
- "clearLocalStorage"
- TizenWebViewController has no implementation.
- Remove unused code in webview.cc
=> [webview_flutter] Clean up integration test and unused code

tools/lib/src/integration_test_command.dart
Connecting to GitHub often fails with a "Connection timed out" error on our integration test server ([example](https://github.com/flutter-tizen/plugins/actions/runs/4684855976/attempts/4)). Automatically retry a maximum of 5 times before throwing a `ToolExit` error.
=> [tool] Retry when the precache command failed

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/example/integration_test/webview_flutter_test.dart, packages/webview_flutter/lib/src/tizen_webview.dart, packages/webview_flutter/lib/src/tizen_webview_controller.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
Support post requests with header and body using ewk_view_url_request_set() API.
=> [webview_flutter] Implement LoadRequestMethod.post feature

packages/messageport/CHANGELOG.md, packages/messageport/example/integration_test/messageport_test.dart, packages/messageport/pubspec.yaml, packages/messageport/tizen/src/messageport_tizen_plugin.cc
`null` is a valid message type as specified in the README.
The tizen_app_control example's dependency should be updated after releasing this change.
=> [messageport] Fix PlatformException when sending a null message

packages/sqflite/CHANGELOG.md, packages/sqflite/README.md, packages/sqflite/example/pubspec.yaml, packages/sqflite/lib/sqflite_tizen.dart, packages/sqflite/pubspec.yaml
Fixes the "databaseFactory not initialized" CI error caused by [this recent change](https://github.com/tekartik/sqflite/commit/42fc7e279b80169ec146c755ec91764680efe3e8) in the plugin API.
=> [sqflite] Set the default factory implementation

packages/package_info_plus/CHANGELOG.md, packages/package_info_plus/README.md, packages/package_info_plus/example/integration_test/package_info_plus_test.dart, packages/package_info_plus/example/lib/main.dart, packages/package_info_plus/example/pubspec.yaml, packages/package_info_plus/pubspec.yaml, packages/package_info_plus/tizen/src/package_info_plus_tizen_plugin.cc
* Update package_info_plus to 4.0.1.
* Update package_info_plus_platform_interface to 2.0.1.
* Update flutter_lints to 2.0.1.
* Update the example app and integration_test.
* Let `buildNumber` return an empty string.
=> [package_info_plus] Update dependencies

.github/workflows/release.yml, tools/lib/src/build_examples_command.dart, tools/lib/src/integration_test_command.dart, tools/lib/src/publish_command.dart, tools/pubspec.yaml
The pub cache location has changed in Dart 3.0.
This change should land as soon as possible to fix our [broken CI](https://github.com/flutter-tizen/plugins/actions/runs/5091477987).
Reference: https://github.com/flutter/packages/commit/5b7d732939860d38aeb6d255aa23713788c9833d
=> [tool] Use new pub cache location for the publish command

packages/battery_plus/CHANGELOG.md, packages/battery_plus/README.md, packages/battery_plus/pubspec.yaml, packages/battery_plus/tizen/src/battery_plus_tizen_plugin.cc, packages/connectivity_plus/CHANGELOG.md, packages/connectivity_plus/README.md, packages/connectivity_plus/pubspec.yaml, packages/connectivity_plus/tizen/src/connectivity_plus_tizen_plugin.cc, packages/geolocator/CHANGELOG.md, packages/geolocator/README.md, packages/geolocator/pubspec.yaml, packages/geolocator/tizen/src/geolocator_tizen_plugin.cc, packages/messageport/CHANGELOG.md, packages/messageport/pubspec.yaml, packages/messageport/tizen/src/messageport_tizen_plugin.cc, packages/sensors_plus/CHANGELOG.md, packages/sensors_plus/README.md, packages/sensors_plus/pubspec.yaml, packages/sensors_plus/tizen/src/sensors_plus_plugin.cc, packages/tizen_rpc_port/CHANGELOG.md, packages/tizen_rpc_port/README.md, packages/tizen_rpc_port/pubspec.yaml, packages/tizen_rpc_port/tizen/src/tizen_rpc_port_plugin.cc, packages/wearable_rotary/CHANGELOG.md, packages/wearable_rotary/README.md, packages/wearable_rotary/pubspec.yaml, packages/wearable_rotary/tizen/src/wearable_rotary_plugin.cc
This reverts https://github.com/flutter-tizen/plugins/pull/455.
The extended classes generate compile errors on Flutter 3.10 because they use the `StreamHandlerError` constructor. The constructor takes `std::unique_ptr&&` instead of a plain pointer since Flutter 3.10.
```cpp
src/messageport_tizen_plugin.cc:56:9: error: no matching constructor for initialization of 'FlStreamHandlerError' (aka 'StreamHandlerError<flutter::EncodableValue>')
FlStreamHandlerError(error_code_, error_message_, error_details) {}
^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/swift/Git/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include/flutter/event_stream_handler.h:23:3: note: candidate constructor not
viable: no known conversion from 'const …
```
=> Remove StreamHandlerError implementations

packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/pubspec.yaml, packages/video_player/tizen/src/video_player.cc
OnVideoFrameDecoded callback may be received during destory MM player. So check is_initialized_ value when receive frame decoded callback.
=> [video_player] Fix memory leak issue

packages/tizen_app_control/CHANGELOG.md, packages/tizen_app_control/README.md, packages/tizen_app_control/lib/src/app_control.dart, packages/tizen_app_control/lib/src/ffi.dart, packages/tizen_app_control/pubspec.yaml
Add inhouse APIs related to the auto-restart feature as requested by an internal developer.
I don't have a Tizen 7.0 device that supports this feature. @hjhun Could you test the code?
Below is simple example code for testing. You can use the Send SMS and Pick image buttons to activate and deactivate the auto-restart setting.
```patch
diff --git a/packages/tizen_app_control/example/lib/main.dart b/packages/tizen_app_control/example/lib/main.dart
index ee06f16c..6d6fda84 100644
--- a/packages/tizen_app_control/example/lib/main.dart
+++ b/packages/tizen_app_control/example/lib/main.dart
@@ -87,9 +87,18 @@ class _MyAppState extends State<MyApp> {
super.dispose();
_localPort?.unregister();
+
+    AppControl.onAppControl.listen((ReceivedAppControl request) {
+      print('Received extra data: …
```
=> [tizen_app_control] Add static setAutoRestart method

packages/camera/tizen/src/camera_device.cc, packages/flutter_webrtc/tizen/src/flutter_video_renderer.cc, packages/video_player/tizen/src/video_player.cc, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter_lwe/tizen/src/webview.cc
`UnregisterTexture(texture_id)` is deprecated [as of Flutter 3.7](https://github.com/flutter-tizen/embedder/pull/21) and `UnregisterTexture(texture_id, callback)` should be used instead.
=> Update deprecated UnregisterTexture usage

packages/wakelock/CHANGELOG.md, packages/wakelock/README.md, packages/wakelock/analysis_options.yaml, packages/wakelock/example/pubspec.yaml, packages/wakelock/lib/wakelock_tizen.dart, packages/wakelock/pubspec.yaml, packages/wakelock/tizen/src/wakelock_tizen_plugin.cc
Why use basic message channel instead of a method channel?
Contributes to https://github.com/flutter-tizen/plugins/issues/354.
=> [wakelock] Refactor and simplify the implementation

README.md, packages/flutter_webrtc/README.md, packages/video_player_videohole/README.md
Remove the API level column from the device limitations table as it doesn't add much useful information (there are now only two packages that require Tizen 6.0 or higher).
Also mark video_player_videohole as "[partially supported](https://github.com/flutter-tizen/plugins/issues/304#issuecomment-1592635340)" on TV emulator.
=> Remove API level info from README

packages/image_picker/CHANGELOG.md, packages/image_picker/example/pubspec.yaml
- Fix `video_player` dependency in example to `>=2.1.4 <2.7.0`
- `VideoPlayerController.network` is deprecated since version 2.7.0 in video_player plugin. ([link](https://pub.dev/packages/video_player/changelog))
=> [image_picker] Fix video_player dependency in example

packages/shared_preferences/CHANGELOG.md, packages/shared_preferences/README.md, packages/shared_preferences/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/example/pubspec.yaml, packages/shared_preferences/lib/shared_preferences_tizen.dart, packages/shared_preferences/pubspec.yaml
- Update shared_preferences to 2.2.0.
- Update shared_preferences_platform_interface to 2.3.0.
- Implement `clearWithParameters` and `getAllWithParameters`
- Update integration_test.
=> [shared_preferences] Update to support shared_preferences 2.2.0

packages/audioplayers/example/lib/tabs/audio_context.dart, packages/audioplayers/example/lib/tabs/controls.dart, packages/audioplayers/example/lib/tabs/logger.dart, packages/flutter_secure_storage/example/lib/main.dart, packages/sqflite/analysis_options.yaml
Resolves https://github.com/flutter-tizen/plugins/issues/609.
=> Resolve Flutter 3.13 analyze issues

packages/sqflite/CHANGELOG.md, packages/sqflite/README.md, packages/sqflite/analysis_options.yaml, packages/sqflite/example/analysis_options.yaml, packages/sqflite/example/lib/batch_test_page.dart, packages/sqflite/example/lib/database/database.dart, packages/sqflite/example/lib/database/database_impl.dart, packages/sqflite/example/lib/database/database_io.dart, packages/sqflite/example/lib/database/database_web.dart, packages/sqflite/example/lib/exception_test_page.dart, packages/sqflite/example/lib/exp_test_page.dart, packages/sqflite/example/lib/main.dart, packages/sqflite/example/lib/manual_test_page.dart, packages/sqflite/example/lib/model/item.dart, packages/sqflite/example/lib/open_test_page.dart, packages/sqflite/example/lib/raw_test_page.dart, packages/sqflite/example/lib/slow_test_page.dart, packages/sqflite/example/lib/src/common_import.dart, packages/sqflite/example/lib/src/expect.dart, packages/sqflite/example/lib/src/item_widget.dart, packages/sqflite/example/lib/src/main_item_widget.dart, packages/sqflite/example/lib/test_page.dart, packages/sqflite/example/lib/type_test_page.dart, packages/sqflite/example/lib/utils.dart, packages/sqflite/example/pubspec.yaml, packages/sqflite/pubspec.yaml
* Update sqflite to 2.3.0
* Increase the minimum Flutter version to 3.3.
* Increase the minimum sdk version to 3.0.0.
Related to #609
=> [sqflite] Update sqflite to 2.3.0

packages/sqflite/example/lib/manual_test_page.dart
Fix analyze error in CI. This patch is taken from here.
https://github.com/tekartik/sqflite/commit/c0defa9f622757fb135b006d10242f925b22fdc1
issue : https://github.com/flutter-tizen/plugins/actions/runs/6886746651/job/18732875305?pr=625#step:4:826
=> [sqflite] Remove deprecated WillPopScope

packages/device_info_plus/CHANGELOG.md, packages/device_info_plus/README.md, packages/device_info_plus/example/integration_test/device_info_plus_test.dart, packages/device_info_plus/example/lib/main.dart, packages/device_info_plus/example/pubspec.yaml, packages/device_info_plus/lib/device_info_plus_tizen.dart, packages/device_info_plus/pubspec.yaml, packages/device_info_plus/tizen/src/device_info_plus_tizen_plugin.cc
- Add `TizenDeviceInfo.data` which represents the device info as a map. ([source](https://github.com/fluttercommunity/plus_plugins/blob/a246de0323c454b0a89dfa0fc1ba6e7aa58ef477/packages/device_info_plus/device_info_plus_platform_interface/lib/model/base_device_info.dart#L7))
- Disambiguate the method channel name to avoid a possible conflict with the original device_info_plus.
=> [device_info_plus] Add TizenDeviceInfo.data property

packages/integration_test/CHANGELOG.md, packages/integration_test/README.md, packages/integration_test/pubspec.yaml, packages/integration_test/tizen/src/integration_test_plugin.cc
This is the oldest of our released packages.
https://pub.dev/packages?q=publisher%3Atizen.org&sort=updated
=> [integration_test] Version bump to 2.0.2

packages/network_info_plus/CHANGELOG.md, packages/network_info_plus/README.md, packages/network_info_plus/example/integration_test/network_info_plus_test.dart, packages/network_info_plus/example/lib/main.dart, packages/network_info_plus/example/pubspec.yaml, packages/network_info_plus/pubspec.yaml
Update network_info_plus to 4.1.0.
Update network_info_plus_platform_interface to 1.1.3.
Increase the minimum Flutter version to 3.3.
=> [network_info_plus] Update network_info_plus to 4.1.0

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/example/integration_test/webview_flutter_test.dart, packages/webview_flutter/example/lib/main.dart, packages/webview_flutter/example/pubspec.yaml, packages/webview_flutter/lib/src/tizen_webview.dart, packages/webview_flutter/lib/src/tizen_webview_controller.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/ewk_internal_api_binding.cc, packages/webview_flutter/tizen/src/ewk_internal_api_binding.h, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
* Update webivew_flutter to 4.4.2.
* Update webview_flutter_platform_interface to 2.6.0.
* Adds pub topics to package metadata.
* Adds support to retrieve the user agent. See `TizenWebViewController.getUserAgent`.
* Adds support to register a callback to receive JavaScript console messages. See `TizenWebViewController.setOnConsoleMessage`.
* Apply PlatformView API change.
* Fix bug on playing youtube on TV.
=> [webview_flutter_tizen] Update webview_flutter to 4.4.2

packages/tizen_bundle/CHANGELOG.md, packages/tizen_bundle/lib/tizen_bundle.dart, packages/tizen_rpc_port/CHANGELOG.md, packages/tizen_rpc_port/lib/src/proxy_base.dart, packages/tizen_rpc_port/lib/src/stub_base.dart
related issue : https://github.com/flutter-tizen/plugins/issues/637
=> [tizen_bundle, tizen_rpc_port] Fix token in finalizer to be different from value

.github/workflows/release.yml
bundler install issue that occurred in wait-on-check-action has been fixed.
https://github.com/flutter-tizen/plugins/issues/640
=> [ci] Update wait-on-check-action version to 1.3.3

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/lib/video_player.dart, packages/video_player_avplay/pubspec.yaml, packages/video_player_avplay/tizen/src/plus_player.cc
Issue: there is no video and audio after start play.
1. player should call `SetDisplayVisible` to display one fram after prepare is done.
2. plusplayer don't need to set playback speed when start play, otherwise it will clear buffer and restart buffer.
3. plusplayer can set playback speed when player is pause. Remove code:
```
if (!value.isPlaying) {
return;
}
```
=> [video_player_avplay] Fix not display video issue when start play

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/lib/video_player.dart, packages/video_player_avplay/tizen/src/plus_player.cc
SetVolume()'s state check returns fail even when the state is kPaused.
And _applyVolume called in VideoPlayerController's initialize() is called when the state is kReady, so modify the state check.
=> [video_player_avplay] Fix state check in SetVolume

packages/flutter_secure_storage/example/lib/main.dart, packages/in_app_purchase/example/lib/main.dart, packages/sqflite/example/analysis_options.yaml, packages/sqflite/example/lib/manual_test_page.dart
Fix analyzing issues when upgrade to 3.19 :
- 'always_require_non_null_named_parameters' was removed in Dart '3.3.0'
- Don't use 'BuildContext's across async gaps, guarded by an unrelated 'mounted' check.
- The named parameter 'primary' isn't defined.
=> Resolve Flutter 3.19 analyze issues

analysis_options.yaml, packages/messageport/example/integration_test/messageport_test.dart, packages/messageport/lib/messageport_tizen.dart, packages/video_player_avplay/example/lib/main.dart, packages/video_player_videohole/example/lib/main.dart
Some packages require package upgrade rather than simple modification (ex: google_maps_flutter)
Therefore, the rules below are temporarily ignored.
Any necessary modifications can be applied in a later PR.
https://github.com/flutter/packages/pull/4060
- unnecessary_null_comparison
https://github.com/flutter/packages/pull/4067
- unawaited_futures
https://github.com/flutter/packages/pull/5717
- dangling_library_doc_comments
- no_literal_bool_comparisons
- unnecessary_library_directive
- use_colored_box
- use_enums
- use_string_in_part_of_directives
=> Sync with analysis_options.yaml in flutter/packages

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/lib/src/messages.g.dart, packages/video_player_avplay/lib/src/video_player_tizen.dart, packages/video_player_avplay/lib/video_player.dart, packages/video_player_avplay/lib/video_player_platform_interface.dart, packages/video_player_avplay/pigeons/messages.dart, packages/video_player_avplay/pubspec.yaml, packages/video_player_avplay/tizen/src/media_player.cc, packages/video_player_avplay/tizen/src/messages.cc, packages/video_player_avplay/tizen/src/messages.h, packages/video_player_avplay/tizen/src/plus_player.cc, packages/video_player_avplay/tizen/src/plus_player.h, packages/video_player_avplay/tizen/src/video_player.h, packages/video_player_avplay/tizen/src/video_player_tizen_plugin.cc
```dart  
/// Retrieves a specific property value obtained by the streaming engine (Smooth Streaming, HLS, DASH, or Widevine).
Future<String> getStreamingProperty(StreamingPropertyType type)
````
```dart 
_controller = VideoPlayerController.network(
'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
streamingProperty: <StreamingPropertyType, String>{
StreamingPropertyType.setMode4K: 'true',
StreamingPropertyType.prebufferMode: '50000'
});
``` 
```dart
/// The streaming property type.
enum StreamingPropertyType {
/// HTTP request cookie used to establish the session with the HTTP server.
cookie,
/// HTTP user agent, used in the HTTP request header.
userAgent,
/// Property to initiate prebuffering mode. The second parameter indicates start-time for prebuffered content, in …
```
=> [video_player_avplay] Add get streaming property interface and Update SetStreamingProperty interface

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/lib/src/tizen_webview.dart, packages/webview_flutter/lib/src/tizen_webview_controller.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
There was a case where the ewk engine failed to load on some devices using Tizen 6.0.
As a result, ewk init failed and an engine instance could not be created. We have not found an exact cause for this.
Calling ewk_set_version_policy(1) will solve the problem,
but using UWE(upgrade web engine) in 3rd party application is not recommended.
(The webview works may not be guaranteed to normally.)
Therefore, add a temporary API and have user application call it. 
This API may be deleted in the future depending on whether tizen version 6.0 is supported.
related issue: https://github.com/flutter-tizen/plugins/issues/647
=> [webview_flutter_tizen] Add tizenEnginePolicy extension api temporary

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/tizen/src/plus_player.cc
Plusplayer doesn't support setLoop method, so it will show a error message when calling setLoop method.
Now plsuplayer return true directly and add a instructions in the README.md
=> [video_player_avplay] Remove set looping failed message

packages/geolocator/example/lib/main.dart
background is deprecated, so use surface instead.
=> [geolocator] Fix analyze issue

packages/package_info_plus/CHANGELOG.md, packages/package_info_plus/README.md, packages/package_info_plus/example/pubspec.yaml, packages/package_info_plus/pubspec.yaml
What I did:
- upgrade package_info_plus_platform_interface to 3.0.0
- upgrade package_info_plus to 8.0.0
- update CHANGELOG (min version already 3.13 and 3.1)
- update README
- integration test passed
=> [package_info_plus] upgrade package info plus dependencies

packages/webview_flutter_lwe/CHANGELOG.md, packages/webview_flutter_lwe/README.md, packages/webview_flutter_lwe/lib/src/lwe_webview.dart, packages/webview_flutter_lwe/pubspec.yaml
Previously, javascript channel methods that are called before the webview is created are stored in the pending list.(based on name) Because of that, there was a problem with channels being missing when adding multiple channels.
When the javascript channel method is called,
it is stored differently depending on the name to prevent it from being missed.
```dart
controller
..addJavaScriptChannel(
'method1',...)
..addJavaScriptChannel(
'method2',...);
```
=> [webview_flutter_lwe] Supports multiple JavaScriptChannel method call

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/lib/src/tizen_webview.dart, packages/webview_flutter/pubspec.yaml
The same issue as webview_flutter_lwe. refer to https://github.com/flutter-tizen/plugins/pull/693
This supports the case of calling multiple JavaScriptChannel methods.
=> [webview_flutter_tizen] Supports multiple JavaScriptChannel method call

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/tizen/src/webview.cc, packages/webview_flutter/tizen/src/webview.h
Dispose() is called redundantly on destructor and PlatformView.
Modify it to only operate once.
+) Minor fix - Do `setEnginePolicy` method call and returns immediately. It prevents duplicate calls to `result`.
=> [webview_flutter_tizen] Prevent duplicate Dispose() calls

packages/shared_preferences/CHANGELOG.md, packages/shared_preferences/README.md, packages/shared_preferences/lib/shared_preferences_tizen.dart, packages/shared_preferences/pubspec.yaml
Creating a release for https://github.com/flutter-tizen/plugins/pull/700. Also update the outdated tizen_interop version.
=> [shared_preferences] Update tizen_interop to 0.3.0

packages/tizen_bundle/CHANGELOG.md, packages/tizen_bundle/README.md, packages/tizen_bundle/lib/tizen_bundle.dart, packages/tizen_bundle/pubspec.yaml
Update tizen_interop version.
https://github.com/flutter-tizen/plugins/issues/704
=> [tizen_bundle] Update tizen_interop to 0.3.0

packages/tizen_app_manager/CHANGELOG.md, packages/tizen_app_manager/README.md, packages/tizen_app_manager/lib/src/app_context.dart, packages/tizen_app_manager/pubspec.yaml
Update tizen_interop version.
https://github.com/flutter-tizen/plugins/issues/704
=> [tizen_app_manager] Update tizen_interop to 0.3.0

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/tizen/src/webview.cc
ewk_init() and ewk_shutdown() are designed to be called only once in a process.
(If ewk_init() is called after ewk_shutdown() is called, SIGTRAP is called internally.)
ewk_init() initializes the efl module and web engine's arguments data.
The efl module is initialized by default in OS, and Arguments data is also initialized
through SetArguments() API, so calling ewk_init() is not necessary.
Therefore, temporarily comment out ewk_init() and ewk_shutdown().
It can be reverted depending on updates to chromium-efl. ewk_init();
related issue: https://github.com/flutter-tizen/plugins/issues/697
=> [webview_flutter] Disable unnecessary web-engine initialization

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/README.md, packages/google_maps_flutter/lib/src/google_maps_controller.dart, packages/google_maps_flutter/pubspec.yaml
GoogleMaps interface has a longpress event, but Google Javascript API does not provide a longpress event.
The existing code implemented longpress using the rightclick event,
but the rightclick event was deprecated when the Javascript API of Google Maps was updated. (https://developers.google.com/maps/documentation/javascript/reference/map#Map.rightclick)
Therefore, Implement longpress event using mousedown/up events.
=> [google_maps_flutter] Support longpress event

packages/flutter_secure_storage/CHANGELOG.md, packages/flutter_secure_storage/tizen/src/secure_storage.cc
This PR addresses an issue that caused the application to crash when attempting to encrypt or decrypt an empty string.
- **Encrypt Method:**
- Added a check to return a vector containing a single null byte when the input string is empty. This ensures that the function handles empty inputs without errors.
- **Decrypt Method:**
- Added a check to return an empty string when the input vector size is less than or equal to the initialization vector size. This prevents errors during decryption when the input is insufficient.
- Verified that attempting to encrypt or decrypt an empty string no longer causes the application to crash.
- To test with the example app, edit the value in the text field, remove all content to make it an empty string, and then save it. The application should handle this …
=> [flutter_secure_storage] Fix Crashes on Encrypting/Decrypting Empty Strings

packages/battery_plus/CHANGELOG.md, packages/battery_plus/example/lib/main.dart
Resolve following issues:
```
info • example/lib/main.dart:78:23 • Don't use 'BuildContext's across async gaps. Try rewriting the code to not use the 'BuildContext', or guard the use with a 'mounted' check. •
use_build_context_synchronously
info • example/lib/main.dart:102:23 • Don't use 'BuildContext's across async gaps. Try rewriting the code to not use the 'BuildContext', or guard the use with a 'mounted' check. •
use_build_context_synchronously
```
=> [battery_plus] Fix analyze issue

packages/permission_handler/CHANGELOG.md, packages/permission_handler/example/lib/main.dart
Resolve following issues:
```
info • example/lib/main.dart:19:7 • Constructors for public widgets should have a named 'key' parameter. Try adding a named parameter to the constructor. • use_key_in_widget_constructors
info • example/lib/main.dart:72:9 • Constructors for public widgets should have a named 'key' parameter. Try adding a named parameter to the constructor. • use_key_in_widget_constructors
info • example/lib/main.dart:77:37 • Don't put any logic in 'createState'. Try moving the logic out of 'createState'. • no_logic_in_create_state
info • example/lib/main.dart:150:7 • Don't invoke 'print' in production code. Try using a logging framework. • avoid_print
info • example/lib/main.dart:152:7 • Don't invoke 'print' in production code. Try using a logging framework. • avoid_print
```
=> [permission_handler] Fix analyze issue

packages/sensors_plus/CHANGELOG.md, packages/sensors_plus/example/lib/main.dart
Resolve following issues:
```
info • example/lib/main.dart:250:15 • Don't use 'BuildContext's across async gaps. Try rewriting the code to not use the 'BuildContext', or guard the use with a 'mounted' check. •
use_build_context_synchronously
info • example/lib/main.dart:279:15 • Don't use 'BuildContext's across async gaps. Try rewriting the code to not use the 'BuildContext', or guard the use with a 'mounted' check. •
use_build_context_synchronously
info • example/lib/main.dart:308:15 • Don't use 'BuildContext's across async gaps. Try rewriting the code to not use the 'BuildContext', or guard the use with a 'mounted' check. •
use_build_context_synchronously
info • example/lib/main.dart:337:15 • Don't use 'BuildContext's across async gaps. Try rewriting the code to not use the …
```
=> [sensors_plus] Fix analyze issue

packages/flutter_webrtc/CHANGELOG.md, packages/flutter_webrtc/example/flutter_webrtc_demo/lib/src/utils/screen_select_dialog.dart, packages/flutter_webrtc/example/flutter_webrtc_demo/lib/src/widgets/screen_select_dialog.dart, packages/flutter_webrtc/example/flutter_webrtc_example/lib/main.dart, packages/flutter_webrtc/example/flutter_webrtc_example/lib/src/get_display_media_sample.dart, packages/flutter_webrtc/example/flutter_webrtc_example/lib/src/loopback_sample_unified_tracks.dart, packages/flutter_webrtc/example/flutter_webrtc_example/lib/src/widgets/screen_select_dialog.dart
Resolve following issues:
```
error • example/flutter_webrtc_example/lib/main.dart:31:59 • There's no constant named 'Default' in 'AndroidNotificationImportance'. Try correcting the name to the name of an existing constant, or
defining a constant named 'Default'. • undefined_enum_constant
error • example/flutter_webrtc_example/lib/src/get_display_media_sample.dart:64:41 • Invalid constant value. • invalid_constant error • example/flutter_webrtc_example/lib/src/get_display_media_sample.dart:64:71 • There's no constant named 'Default' in 'AndroidNotificationImportance'. Try correcting the name to the name of an
existing constant, or defining a constant named 'Default'. • undefined_enum_constant
info • example/flutter_webrtc_demo/lib/src/utils/screen_select_dialog.dart:279:22 • 'ButtonBar' …
```
=> [flutter_webrtc] Fix analyze issue

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/lib/src/messages.g.dart, packages/video_player_avplay/lib/src/video_player_tizen.dart, packages/video_player_avplay/lib/video_player.dart, packages/video_player_avplay/lib/video_player_platform_interface.dart, packages/video_player_avplay/pigeons/messages.dart, packages/video_player_avplay/pubspec.yaml, packages/video_player_avplay/tizen/src/messages.cc, packages/video_player_avplay/tizen/src/messages.h, packages/video_player_avplay/tizen/src/plus_player.cc, packages/video_player_avplay/tizen/src/plus_player.h, packages/video_player_avplay/tizen/src/video_player.h, packages/video_player_avplay/tizen/src/video_player_tizen_plugin.cc
Add a new interface
```dart
/// Sets the buffer size for the play and resume scenarios. The time buffer size must be at least 4 seconds.
/// For example, if a 10 second buffer size is set, playback can only start or resume after 10 seconds of media has accumulated in the buffer.
/// Play scenarios include user-initiated streaming playback and whenever media playback is starting for the first time.
/// Resume scenarios include resuming playback after pause or seek operations, or when lack of data causes playback rebuffering.
setBufferConfig(BufferConfigType type, int value)
```
=> [video_player_avplay] Add setBufferConfig interface

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/lib/src/messages.g.dart, packages/video_player_avplay/lib/src/video_player_tizen.dart, packages/video_player_avplay/pigeons/messages.dart, packages/video_player_avplay/tizen/src/messages.cc, packages/video_player_avplay/tizen/src/messages.h, packages/video_player_avplay/tizen/src/plus_player.cc, packages/video_player_avplay/tizen/src/video_player_tizen_plugin.cc
From SetStreamingProperty API guide:
```
/**
* @brief     Set streamingengine property
* @param     [in] type : attribute type. \n
*             type can be \n
*               "COOKIE" \n
*               "USER_AGENT" \n
*               "RESUME_TIME" \n
*               "ADAPTIVE_INFO"
* @param     [in] value : value of attribute type
* @pre       The player state can be all of #State except #State::kNone
*/
``` 
We need call open first, then call SetStreamingProperty.
=> [video_player_avplay] Call the open before calling the SetStreamingProperty

packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/example/integration_test/video_player_test.dart, packages/video_player/example/lib/main.dart, packages/video_player/example/pubspec.yaml, packages/video_player/lib/video_player_tizen.dart, packages/video_player/pubspec.yaml, packages/video_player/tizen/src/video_player.cc, packages/video_player/tizen/src/video_player.h
* Update video_player to 2.9.1.
* Update video_player_platform_interface to 6.2.0.
* Update the example app and integration_test.
* Fix new lint warnings.
* Update minimum Flutter and Dart version to 3.19 and 3.3.
* Synchronizes VideoPlayerValue.isPlaying with underlying video player.
issue: https://github.com/flutter-tizen/plugins/issues/727
=> [video_player] Update video_player to 2.5.0

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/lib/src/messages.g.dart, packages/video_player_avplay/lib/src/video_player_tizen.dart, packages/video_player_avplay/lib/video_player.dart, packages/video_player_avplay/lib/video_player_platform_interface.dart, packages/video_player_avplay/pigeons/messages.dart, packages/video_player_avplay/pubspec.yaml, packages/video_player_avplay/tizen/src/messages.cc, packages/video_player_avplay/tizen/src/messages.h, packages/video_player_avplay/tizen/src/plus_player.cc, packages/video_player_avplay/tizen/src/plus_player.h, packages/video_player_avplay/tizen/src/video_player.h, packages/video_player_avplay/tizen/src/video_player_tizen_plugin.cc
Add setStreamingProperty API:
```dart
/// Sets specific feature values for HTTP, MMS, or specific streaming engine (Smooth Streaming, HLS, DASH, DivX Plus Streaming, or Widevine).
/// The available streaming properties depend on the streaming protocol or engine.
/// Use the CUSTOM_MESSAGE property for streaming engine or CP-specific settings.
Future<void> setStreamingProperty(StreamingPropertyType type, String value) ;
```
Native interface:
```C++
/**
* @brief     Set streamingengine property
* @param     [in] type : attribute type. \n
*             type can be \n
*               "COOKIE" \n
*               "USER_AGENT" \n
*               "RESUME_TIME" \n
*               "ADAPTIVE_INFO"
* @param     [in] value : value of attribute type
* @pre       The player state can be all of #State …
```
=> [video_player_avplay] Add setStreamingProperty API

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/lib/src/google_maps_flutter_tizen.dart, packages/google_maps_flutter/pubspec.yaml
google_maps_flutter plugin was updated to 2.9.0 and new APIs were also added. Due to this, Unimplemented Error and Crash occur.
Therefore, temporary code is added to prevent these errors until implementation. (In addition, this commit must be merged after webview_flutter_lwe 0.3.3 is applied)
=> [google_maps_flutter] Add temporary code to prevent errors

packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/pubspec.yaml, packages/video_player/tizen/src/video_player.cc, packages/video_player/tizen/src/video_player.h, packages/video_player/tizen/src/video_player_tizen_plugin.cc
Only support [`Cookie`](https://docs.tizen.org/application/native/api/common/8.0/group__CAPI__MEDIA__PLAYER__STREAMING__MODULE.html#ga47e7c7488b68d522a20cd8853096a339) and [`User-Agent`](https://docs.tizen.org/application/native/api/common/8.0/group__CAPI__MEDIA__PLAYER__STREAMING__MODULE.html#ga4e4bbf1511b9a7c560313ccf2f465cf0).
=> [video_player] Support httpHeaders option of VideoPlayerController.network

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/lib/src/tracks.dart, packages/video_player_avplay/lib/src/video_player_tizen.dart, packages/video_player_avplay/pubspec.yaml
Checked with MM team, the audio track channel range is 2 ~ 12, the AudioTrackChannelType is not suitable for use here, so return channel directly.
```dart
enum AudioTrackChannelType {
/// The mono channel.
mono,
/// The stereo channel.
stereo,
/// The surround channel.
surround,
}
```
=> [video_player_avplay] Fix getAudioTracks out of bounds issue

packages/path_provider/CHANGELOG.md, packages/path_provider/README.md, packages/path_provider/example/integration_test/path_provider_test.dart, packages/path_provider/example/lib/main.dart, packages/path_provider/example/pubspec.yaml, packages/path_provider/lib/path_provider_tizen.dart, packages/path_provider/pubspec.yaml
* Update path_provider to 2.1.4.
* Update path_provider_platform_interface to 2.1.2.
* Adds getApplicationCachePath() for storing app-specific cache files.
* Update minimum Flutter and Dart version to 3.19 and 3.3.
=> [path_provider] Update path_provider to 2.1.4

.github/workflows/build.yml, tools/lib/src/build_examples_command.dart, tools/pubspec.yaml, tools/test_data/foo/example/pubspec.yaml, tools/test_data/foo/pubspec.yaml
Older Dart SDK Versions are deprecated. So sdk version must be upgraded to 3.0 or higher.
https://groups.google.com/g/flutter-announce/c/JQHzM3FbBGI/m/B-i8IVa1AQAJ
+) For wearable_rotary, it is no longer updated, but it runs together with the build test of CI due to the change in tools.
Since it causes a break in CI, so temporarily skip the build of wearable_rotary.
=> [tools] Bump up sdk version

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/pubspec.yaml, packages/video_player_avplay/tizen/src/plus_player.cc
Add start position in player options when creating player,this is useful for resuming playback from last viewed position.
code sample:
```dart
_controller = VideoPlayerController.network(
'https://media.w3.org/2010/05/bunny/trailer.mp4',
// startPosition in millisecond
playerOptions: {'startPosition': 10 * 1000});
```
=> [video_player_avplay] Add start position in player options when creating player

packages/audioplayers/CHANGELOG.md, packages/audioplayers/README.md, packages/audioplayers/pubspec.yaml, packages/audioplayers/tizen/src/audio_player.cc
When setSource() is called, or setSource() is called when play() is called,
it waits for the event of AudioEventType.prepared. If the url has not been set
or a different url is set than before, it calls the prepared event, but if the url is the same,
it does not call the event and waits for preparedCompeter. Therefore, regardless of whether the url is set,
it always resets the player and calls preparePlayer().
=> [audioplayers] Fix play() didn't work after setSource()

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/lib/src/google_maps_controller.dart
When using a google map's addListener(), do not call the Javascript object directly. This extremely increases memory usage.
Do:
map.addListener('bounds_changed', (event) => { BoundChanged.postMessage('') });
Do not:
map.addListener('bounds_changed', BoundChanged.postMessage);
=> [google_maps_flutter] Fix memory alarm and map initialization issue

packages/connectivity_plus/CHANGELOG.md, packages/connectivity_plus/README.md, packages/connectivity_plus/example/lib/main.dart, packages/connectivity_plus/example/pubspec.yaml, packages/connectivity_plus/pubspec.yaml, packages/connectivity_plus/tizen/src/connectivity_plus_tizen_plugin.cc
- Update connectivity_plus to 6.1.0.
- Update connectivity_plus_platform_interface to 2.0.1.
- 
https://github.com/flutter-tizen/plugins/issues/758
=> [connectivity_plus] Update connectivity_plus to 6.1.0

packages/flutter_tts/CHANGELOG.md, packages/flutter_tts/README.md, packages/flutter_tts/example/lib/main.dart, packages/flutter_tts/example/pubspec.yaml, packages/flutter_tts/pubspec.yaml, packages/flutter_tts/tizen/src/flutter_tts_tizen_plugin.cc, packages/flutter_tts/tizen/src/text_to_speech.cc, packages/flutter_tts/tizen/src/text_to_speech.h
Update flutter_tts 3.6.3 to 4.2.0.
Update the example app.
Add isLanguageAvailable, getVoices and setVoice APIs which were not implemented.
=> [flutter_tts] Update flutter_tts to 4.2.0

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/pubspec.yaml, packages/video_player_avplay/tizen/src/plus_player.cc
The startPosition could be int64_t or int32_t, we need to support both.
=> [ video_player_avplay] Make startPosition support int32_t

packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/example/pubspec.yaml, packages/video_player/pubspec.yaml
* Update video_player to 2.9.2.
* Update video_player_platform_interface to 6.2.3.
+) Fix readme typo
=> [video_player] Update video_player to 2.9.2

packages/camera/example/lib/main.dart, packages/in_app_purchase/lib/src/billing_manager_wrappers/billing_manager_wrapper.dart
camera - Remove unnecessary 'break' statement.
in_app_purchase - Remove unreachable siwtch default case.
https://github.com/flutter-tizen/plugins/actions/runs/12425999862/job/34693630064
=> [camera, in_app_purchase] Fix new lint warnings

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/lib/src/messages.g.dart, packages/video_player_avplay/lib/src/video_player_tizen.dart, packages/video_player_avplay/lib/video_player.dart, packages/video_player_avplay/lib/video_player_platform_interface.dart, packages/video_player_avplay/pigeons/messages.dart, packages/video_player_avplay/pubspec.yaml, packages/video_player_avplay/tizen/src/media_player.cc, packages/video_player_avplay/tizen/src/media_player.h, packages/video_player_avplay/tizen/src/messages.cc, packages/video_player_avplay/tizen/src/messages.h, packages/video_player_avplay/tizen/src/plus_player.cc, packages/video_player_avplay/tizen/src/plus_player.h, packages/video_player_avplay/tizen/src/video_player.h, packages/video_player_avplay/tizen/src/video_player_tizen_plugin.cc
```dart
/// Set the rotate angle of display
Future<bool> setDisplayRotate(DisplayRotation rotation)
```
```dart
/// Set the video display mode.
Future<bool> setDisplayMode(DisplayMode displayMode)
```
=> [video_player_avplay] Add setDisplayMode and setDisplayRotate API

.github/workflows/build.yml
[ubuntu-latest(24.04)](https://github.com/actions/runner-images/issues/10636) no longer supports installing python 2.7 packages.
Tizen package manager still requires python2.7, so I add the python repository for this.
deadsnakes is an unofficial repository, but it is already being used by many users.
https://github.com/flutter-tizen/plugins/actions/runs/12707342335/job/35422168443#step:5:205
=> [ci] Fix python2.7 installation error

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/lib/video_player.dart, packages/video_player_avplay/pubspec.yaml
Add a step to the initialization phase that compares the API version of the app using avplay with the version of TizenOS.
This prevents TPKs built with avplay from running on TizenOS versions for which they are not intended.
related issue: https://github.com/flutter-tizen/plugins/issues/786
=> [video_player_avplay] Add check platform and api version

.github/workflows/analyze.yml, .github/workflows/build.yml, .github/workflows/pull_request_label.yml, .github/workflows/release.yml
Tizen studio requires python 2.7 and libncurses5. However, Ubuntu 24.04's apt no longer supports these packages. I considered options like deadsnake(24.04), but python 2.7 is no longer supported. Rather than installing this manually, I decided that tizen studio is not ready for 24.04 yet, so I fixed the version of ubuntu runnner to 22.04.
=> [ci] Change ubuntu runner to 22.04

packages/url_launcher/CHANGELOG.md, packages/url_launcher/README.md, packages/url_launcher/example/lib/main.dart, packages/url_launcher/example/pubspec.yaml, packages/url_launcher/lib/url_launcher_tizen.dart, packages/url_launcher/pubspec.yaml
* Update minimum Flutter and Dart version to 3.19 and 3.3.
* Remove `file` scheme from supportedSchemes.
* Update the example app.
* Update url_launcher to 6.3.1.
* Update url_launcher_platform_interface to 2.3.2.
=> [url_launcher] Update url_launcher to 6.3.1

packages/video_player/CHANGELOG.md, packages/video_player/lib/video_player_tizen.dart
A parameter has been renamed in the platform interface, which causes an analyser issue. (https://github.com/flutter/packages/pull/8453)
This should be updated when platform view of video_player is supported.
=> [video_player] Add ignore analyzer option to fix analyze warning

packages/webview_flutter_lwe/CHANGELOG.md, packages/webview_flutter_lwe/README.md, packages/webview_flutter_lwe/example/lib/main.dart, packages/webview_flutter_lwe/example/pubspec.yaml, packages/webview_flutter_lwe/lib/src/lwe_webview.dart, packages/webview_flutter_lwe/lib/src/lwe_webview_controller.dart, packages/webview_flutter_lwe/pubspec.yaml, packages/webview_flutter_lwe/tizen/src/message_dispatcher.cc, packages/webview_flutter_lwe/tizen/src/webview.cc, packages/webview_flutter_lwe/tizen/src/webview.h
* Update minimum Flutter and Dart version to 3.24 and 3.5.
* Update the example main app.
* Update webview_flutter to 4.10.0.
* Update webview_flutter_platform_interface to 2.10.0.
* Add removeJavaScriptChannel method call.
* Fix deadlock issue caused by calling setBackgroundColor() after the WebViewController is created.
=> [webview_flutter_lwe] Update webview_flutter to 4.10.0

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md, packages/video_player_avplay/lib/video_player.dart, packages/video_player_avplay/pubspec.yaml
We already provide rotate API for video player,
but it seems like a bug that the video player's video image doesn't rotate according to the device orientation. So we should automatically change this inside video_player. When user call the API, the video image may rotate, but when the device's orientation changes, the rotation may change again.
=> [video_player_avplay] Automatically rotates video player based on device orientation

packages/video_player_avplay/CHANGELOG.md, packages/video_player_avplay/README.md
Add more information about version compatibility.
=> [video_player_avplay] Update readme

packages/connectivity_plus/CHANGELOG.md, packages/connectivity_plus/README.md, packages/connectivity_plus/pubspec.yaml, packages/connectivity_plus/tizen/src/connection.cc, packages/connectivity_plus/tizen/src/connection.h
- Clarify ConnectivityResult.none type
- `ConnectivityResult.none type` is a disconnected situation, so make sure to only return the `connection_type_e.CONNECTION_TYPE_DISCONNECTED` type.
- Update plugin requirements version in README.
- This change was missing in #764. If you use version ^4.0.1, you will get a version solving failed error.
=> [connectivity_plus] Clarify ConnectivityResult.none type

.github/workflows/build.yml
As the tizen command of the flutter-tizen tool has changed,
dbus isolation is required inside the container.
related pr: https://github.com/flutter-tizen/flutter-tizen/pull/595
=> [ci] Fix signing error in build test

packages/shared_preferences/CHANGELOG.md, packages/shared_preferences/README.md, packages/shared_preferences/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/example/lib/main.dart, packages/shared_preferences/example/pubspec.yaml, packages/shared_preferences/pubspec.yaml
- Update shared_preferences to 2.5.3.
- Update shared_preferences_interface to 2.4.1.
- Update the example app and integration_test. (https://github.com/flutter/packages/pull/8398/files)
- Updates minimum supported SDK version to Flutter 3.27/Dart 3.6.
=> [shared_preferences] Update shared_preferences to 2.5.3

packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/pubspec.yaml, packages/video_player/tizen/src/video_player.cc, packages/video_player/tizen/src/video_player_tizen_plugin.cc
Because pause method thorws VideoPlayerError, if call pause method, we muse be add catch the exception, otherwise the process will call terminate.
```
E/ConsoleMessage( 9835): terminate called after throwing an instance of 'VideoPlayerError'
E/ConsoleMessage( 9835): DotNET onSigabrt called on com.yeelight.station_tv_global
E/ConsoleMessage( 9835): DotNET onSigsegv called
```
=> [video_player] Fix app crash issue

packages/video_player/CHANGELOG.md, packages/video_player/README.md, packages/video_player/example/integration_test/video_player_test.dart, packages/video_player/example/pubspec.yaml, packages/video_player/pubspec.yaml, packages/video_player/tizen/src/video_player.cc, packages/video_player/tizen/src/video_player.h
To prevent crashes, add #ifdef conditions for screensaver code
=> [video_player] Fix integration_test crash issue

packages/device_info_plus/CHANGELOG.md, packages/device_info_plus/README.md, packages/device_info_plus/example/lib/main.dart, packages/device_info_plus/lib/device_info_plus_tizen.dart, packages/device_info_plus/pubspec.yaml, packages/device_info_plus/tizen/src/device_info_plus_tizen_plugin.cc
- Add support for `screenWidth` and `screenHeight`.
related : https://github.com/flutter-tizen/plugins/issues/895
=> [device_info_plus] Add support for `screenWidth` and `screenHeight`

packages/tizen_rpc_port/CHANGELOG.md, packages/tizen_rpc_port/README.md, packages/tizen_rpc_port/pubspec.yaml, packages/tizen_rpc_port/tizen/src/tizen_rpc_port_plugin.cc
- Deploy the updated in #888
- Modifies the conversion of `handle`(If conversion to int64_t fails, it attempts conversion to int32_t again.).
=> [tizen_rpc_port] Update package version to 0.1.5
